"use client";
import { useMemo, useState } from "react";
import { Users, X } from "lucide-react";
import { PageHeader } from "@/components/shell/PageHeader";
import { DataTable, type Column } from "@/components/primitives/DataTable";
import { AsyncBoundary } from "@/components/primitives/AsyncBoundary";
import { ConfirmDialog } from "@/components/primitives/ConfirmDialog";
import { Can } from "@/components/authz/Can";
import { Badge, Card, CardHeader, CardTitle, CardContent, Input } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";
import { FEATURE_GATES } from "@/lib/authz/registry";
import {
  useGroups,
  useGroupMembers,
  useGroupRoles,
  useAddGroupMember,
  useRemoveGroupMember,
  useCreateTeam,
  useUpdateTeam,
  useDeleteTeam,
  useAssignTeamRole,
  useUnassignTeamRole,
  useRoles,
  // Tier 4b: bulk membership (rbac POST /groups/{id}/members:bulk) + directory picker.
  useBulkGroupMembership,
  useUsers,
} from "@/lib/graphql/hooks";
import type { BulkGroupMembershipResult } from "@/lib/graphql/types";
import type { Group } from "@/lib/graphql/types";
import { formatLocal } from "@/lib/utils";

/**
 * Teams = permission-type rbac groups (per-workspace user groupings for role
 * assignment), scoped apart from the general Groups admin screen which also
 * shows content-access groups. See services/rbac-service domain.GroupType.
 */
export default function AdminTeamsPage() {
  const query = useGroups({ type: "permission" });
  const rows = useMemo(() => query.data?.pages.flatMap((p) => p.nodes) ?? [], [query.data]);
  const [selected, setSelected] = useState<Group | null>(null);
  const [creating, setCreating] = useState(false);

  const createTeam = useCreateTeam();

  const columns: Column<Group>[] = [
    { id: "name", header: "Name", cell: (g) => <span className="font-medium">{g.name}</span> },
    {
      id: "kind", header: "Kind", width: 140,
      cell: (g) => g.system
        ? <Badge variant="warning">system</Badge>
        : g.autoGenerated ? <Badge variant="secondary">auto</Badge> : <Badge variant="success">custom</Badge>,
    },
    { id: "desc", header: "Description", cell: (g) => g.description || <span className="text-muted-foreground">—</span> },
  ];

  return (
    <div>
      <PageHeader
        title="Teams"
        description="Permission-type groups (rbac-service) used for role-based membership. Select a team to manage members and role bindings."
        actions={
          <Can gate={FEATURE_GATES.createTeam}>
            <Button onClick={() => setCreating((v) => !v)}>{creating ? "Cancel" : "New team"}</Button>
          </Can>
        }
      />

      {creating && (
        <Card className="mb-4">
          <CardContent className="pt-4">
            <NewTeamForm
              onCreate={(input) =>
                createTeam.mutate(input, {
                  onSuccess: (r) => {
                    setCreating(false);
                    setSelected(r.createTeam);
                  },
                })
              }
              pending={createTeam.isPending}
              error={createTeam.error}
            />
          </CardContent>
        </Card>
      )}

      <div className="grid gap-4 lg:grid-cols-[1fr_400px]">
        <AsyncBoundary
          isLoading={query.isLoading}
          isError={query.isError}
          error={query.error}
          isEmpty={rows.length === 0}
          emptyTitle="No teams yet."
          onRetry={() => query.refetch()}
        >
          <DataTable
            ariaLabel="Teams"
            rows={rows}
            columns={columns}
            rowId={(g) => g.id}
            onRowActivate={(g) => setSelected(g)}
            hasMore={query.hasNextPage}
            isFetchingMore={query.isFetchingNextPage}
            onLoadMore={() => query.fetchNextPage()}
          />
        </AsyncBoundary>

        <TeamDetail team={selected} onClose={() => setSelected(null)} onDeleted={() => setSelected(null)} />
      </div>
    </div>
  );
}

function NewTeamForm({
  onCreate,
  pending,
  error,
}: {
  onCreate: (input: { name: string; description?: string }) => void;
  pending: boolean;
  error: Error | null;
}) {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  return (
    <form
      className="flex flex-wrap items-end gap-2"
      onSubmit={(e) => {
        e.preventDefault();
        if (name.trim()) onCreate({ name: name.trim(), description: description.trim() || undefined });
      }}
    >
      <label className="flex flex-col gap-1 text-sm">
        <span className="text-muted-foreground">Name</span>
        <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Team name" aria-label="Team name" className="w-56" />
      </label>
      <label className="flex flex-col gap-1 text-sm">
        <span className="text-muted-foreground">Description</span>
        <Input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Optional" aria-label="Team description" className="w-72" />
      </label>
      <Button type="submit" disabled={!name.trim() || pending}>Create</Button>
      {error && <p className="w-full text-sm text-destructive">{error.message}</p>}
    </form>
  );
}

function TeamDetail({
  team,
  onClose,
  onDeleted,
}: {
  team: Group | null;
  onClose: () => void;
  onDeleted: () => void;
}) {
  const members = useGroupMembers(team?.id ?? null);
  const addMember = useAddGroupMember(team?.id ?? "");
  const removeMember = useRemoveGroupMember(team?.id ?? "");
  const updateTeam = useUpdateTeam();
  const deleteTeam = useDeleteTeam();
  const assignRole = useAssignTeamRole(team?.id ?? "");
  const unassignRole = useUnassignTeamRole(team?.id ?? "");
  const roles = useRoles();
  const boundRoles = useGroupRoles(team?.id ?? null);

  const [addUserId, setAddUserId] = useState("");
  const [roleId, setRoleId] = useState("");
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(team?.name ?? "");
  const [description, setDescription] = useState(team?.description ?? "");
  const [roleBanner, setRoleBanner] = useState<string | null>(null);
  const [confirmingDelete, setConfirmingDelete] = useState(false);

  const roleOptions = useMemo(() => roles.data?.pages.flatMap((p) => p.nodes) ?? [], [roles.data]);

  if (!team) {
    return (
      <Card className="h-fit">
        <CardHeader><CardTitle className="text-sm">Team detail</CardTitle></CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          <div className="flex flex-col items-center gap-2 py-6 text-center">
            <Users className="size-6" aria-hidden />
            <p>Select a team to see its members and role bindings.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="h-fit">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle className="text-sm">{team.name}</CardTitle>
        <div className="flex items-center gap-1">
          <Can gate={FEATURE_GATES.deleteTeam}>
            <Button variant="ghost" size="sm" disabled={!!team.system} onClick={() => setConfirmingDelete(true)}>
              Delete
            </Button>
          </Can>
          <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close"><X className="size-4" /></Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 text-sm">
        <section className="space-y-2 border-b pb-3">
          {editing ? (
            <form
              className="space-y-2"
              onSubmit={(e) => {
                e.preventDefault();
                updateTeam.mutate(
                  { id: team.id, input: { name: name.trim() || undefined, description } },
                  { onSuccess: () => setEditing(false) },
                );
              }}
            >
              <Input value={name} onChange={(e) => setName(e.target.value)} aria-label="Edit team name" />
              <Input value={description} onChange={(e) => setDescription(e.target.value)} aria-label="Edit team description" placeholder="Description" />
              <div className="flex gap-2">
                <Button type="submit" size="sm" disabled={updateTeam.isPending}>Save</Button>
                <Button type="button" variant="ghost" size="sm" onClick={() => setEditing(false)}>Cancel</Button>
              </div>
              {updateTeam.error && <p className="text-xs text-destructive">{updateTeam.error.message}</p>}
            </form>
          ) : (
            <div className="flex items-center justify-between">
              <p className="text-muted-foreground">{team.description || "No description."}</p>
              <Can gate={FEATURE_GATES.updateTeam}>
                <Button
                  variant="ghost" size="sm" disabled={!!team.system}
                  onClick={() => { setName(team.name); setDescription(team.description ?? ""); setEditing(true); }}
                >
                  Edit
                </Button>
              </Can>
            </div>
          )}
        </section>

        <section className="space-y-2 border-b pb-3">
          <p className="text-xs font-medium uppercase text-muted-foreground">Members</p>
          <AsyncBoundary
            isLoading={members.isLoading}
            isError={members.isError}
            error={members.error}
            isEmpty={(members.data?.length ?? 0) === 0}
            emptyTitle="No members in this team."
            onRetry={() => members.refetch()}
          >
            <ul className="space-y-1">
              {(members.data ?? []).map((m) => (
                <li key={m.userId} className="flex items-center justify-between gap-2 rounded-md border px-2 py-1.5">
                  <div className="min-w-0">
                    <p className="truncate font-mono text-xs">{m.userId}</p>
                    <p className="text-xs text-muted-foreground">
                      joined {formatLocal(m.createdAt)}{m.expiresAt ? ` · expires ${formatLocal(m.expiresAt)}` : ""}
                    </p>
                  </div>
                  <Can gate={FEATURE_GATES.manageGroupMembers}>
                    <Button variant="ghost" size="sm" disabled={removeMember.isPending}
                      onClick={() => removeMember.mutate(m.userId)}>Remove</Button>
                  </Can>
                </li>
              ))}
            </ul>
          </AsyncBoundary>
          <Can gate={FEATURE_GATES.manageGroupMembers}>
            <form
              className="flex items-center gap-2 pt-1"
              onSubmit={(e) => { e.preventDefault(); if (addUserId.trim()) addMember.mutate(addUserId.trim(), { onSuccess: () => setAddUserId("") }); }}
            >
              <Input value={addUserId} onChange={(e) => setAddUserId(e.target.value)} placeholder="user id to add" aria-label="User id to add" className="h-8 text-xs" />
              <Button type="submit" size="sm" disabled={!addUserId.trim() || addMember.isPending}>Add</Button>
            </form>
          </Can>
          <Can gate={FEATURE_GATES.manageGroupMembers}>
            <BulkAddMembers groupId={team.id} />
          </Can>
        </section>

        <section className="space-y-2">
          <p className="text-xs font-medium uppercase text-muted-foreground">Role bindings</p>
          <AsyncBoundary
            isLoading={boundRoles.isLoading}
            isError={boundRoles.isError}
            error={boundRoles.error}
            isEmpty={(boundRoles.data?.length ?? 0) === 0}
            emptyTitle="No roles bound to this team."
            onRetry={() => boundRoles.refetch()}
          >
            <ul className="space-y-1">
              {(boundRoles.data ?? []).map((r) => (
                <li key={r.id} className="flex items-center justify-between gap-2 rounded-md border px-2 py-1.5">
                  <div className="min-w-0">
                    <p className="truncate font-medium">{r.name}</p>
                    <p className="truncate font-mono text-xs text-muted-foreground">{r.id}</p>
                  </div>
                  <Can gate={FEATURE_GATES.assignTeamRole}>
                    <Button
                      variant="ghost" size="sm" disabled={unassignRole.isPending}
                      onClick={() => unassignRole.mutate(r.id, {
                        onSuccess: () => setRoleBanner(`Unbound role ${r.name}`),
                        onError: (e) => setRoleBanner(e.message),
                      })}
                    >
                      Unbind
                    </Button>
                  </Can>
                </li>
              ))}
            </ul>
          </AsyncBoundary>
          <Can gate={FEATURE_GATES.assignTeamRole}>
            <form
              className="flex items-center gap-2 pt-1"
              onSubmit={(e) => {
                e.preventDefault();
                if (roleId) assignRole.mutate(roleId, {
                  onSuccess: () => { setRoleBanner(`Bound role ${roleId}`); setRoleId(""); },
                  onError: (err) => setRoleBanner(err.message),
                });
              }}
            >
              <select
                value={roleId}
                onChange={(e) => setRoleId(e.target.value)}
                aria-label="Role to bind"
                className="h-8 flex-1 rounded-md border border-input bg-background px-2 text-xs"
              >
                <option value="">select a role…</option>
                {roleOptions.map((r) => (
                  <option key={r.id} value={r.id}>{r.name}</option>
                ))}
              </select>
              <Button type="submit" size="sm" disabled={!roleId || assignRole.isPending}>Bind</Button>
            </form>
          </Can>
          {roleBanner && <p role="status" className="text-xs text-muted-foreground">{roleBanner}</p>}
        </section>
      </CardContent>

      <ConfirmDialog
        open={confirmingDelete}
        onOpenChange={setConfirmingDelete}
        title="Delete team"
        description={`Delete the team "${team.name}"? This cannot be undone.`}
        confirmLabel="Delete"
        destructive
        onConfirm={() => {
          deleteTeam.mutate(team.id, {
            onSuccess: onDeleted,
            onSettled: () => setConfirmingDelete(false),
          });
        }}
      />
    </Card>
  );
}

/**
 * Tier 4b: bulk add — multi-select of REAL directory users (identity-service
 * via useUsers) posted as one rbac members:bulk call. The service applies each
 * op independently and reports per-entry outcomes; the {succeeded, failed}
 * shown here is that real report, never a blind success.
 */
function BulkAddMembers({ groupId }: { groupId: string }) {
  const [open, setOpen] = useState(false);
  const [report, setReport] = useState<BulkGroupMembershipResult | null>(null);

  if (!open) {
    return (
      <div className="pt-1">
        <Button variant="outline" size="sm" onClick={() => { setOpen(true); setReport(null); }}>
          Bulk add
        </Button>
        {report && (
          <p role="status" className="mt-1 text-xs text-muted-foreground" data-testid="bulk-result">
            Bulk add: {report.succeeded} succeeded, {report.failed} failed.
            {report.failed > 0 && ` Failures: ${report.results.filter((r) => !r.ok).map((r) => `${r.userId} (${r.code ?? "error"})`).join(", ")}`}
          </p>
        )}
      </div>
    );
  }

  // The directory fetch lives in the expanded picker only — no useUsers call
  // (and no request) until the admin actually opens the bulk-add panel.
  return (
    <BulkAddPicker
      groupId={groupId}
      onDone={(r) => { setReport(r); setOpen(false); }}
      onCancel={() => setOpen(false)}
    />
  );
}

function BulkAddPicker({
  groupId, onDone, onCancel,
}: {
  groupId: string;
  onDone: (r: BulkGroupMembershipResult) => void;
  onCancel: () => void;
}) {
  const [picked, setPicked] = useState<Set<string>>(new Set());
  const [bulkError, setBulkError] = useState<string | null>(null);
  const users = useUsers();
  const bulk = useBulkGroupMembership(groupId);
  const options = useMemo(() => users.data?.pages.flatMap((p) => p.nodes) ?? [], [users.data]);

  const toggle = (id: string) => {
    setPicked((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  return (
    <div className="space-y-2 rounded-md border p-2">
      <p className="text-xs font-medium">Bulk add members</p>
      {users.isLoading ? (
        <p className="text-xs text-muted-foreground">Loading directory…</p>
      ) : options.length === 0 ? (
        <p className="text-xs text-muted-foreground">No users in the directory.</p>
      ) : (
        <ul className="max-h-40 space-y-1 overflow-y-auto">
          {options.map((u) => (
            <li key={u.id}>
              <label className="flex items-center gap-2 text-xs">
                <input
                  type="checkbox"
                  checked={picked.has(u.id)}
                  onChange={() => toggle(u.id)}
                  className="size-3.5 accent-[hsl(var(--primary))]"
                  aria-label={`Select ${u.email}`}
                />
                <span className="truncate">{u.email}</span>
              </label>
            </li>
          ))}
        </ul>
      )}
      {bulkError && <p role="alert" className="text-xs text-destructive">{bulkError}</p>}
      <div className="flex gap-2">
        <Button
          size="sm"
          disabled={picked.size === 0 || bulk.isPending}
          onClick={() =>
            bulk.mutate(
              [...picked].map((userId) => ({ op: "ADD" as const, userId })),
              {
                onSuccess: (r) => { setBulkError(null); onDone(r); },
                onError: (e) => setBulkError(e.message),
              },
            )
          }
        >
          {bulk.isPending ? "Adding…" : `Add ${picked.size || ""} selected`}
        </Button>
        <Button variant="ghost" size="sm" onClick={onCancel}>Cancel</Button>
      </div>
    </div>
  );
}
