import { describe, it, expect, vi, beforeEach } from "vitest";
import { screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { renderWithProviders } from "@/test/utils";

/**
 * Route graphqlRequest by operation name to a per-test handler, same convention
 * as tests/unit/admin.test.ts (bff side) and data/queries/queries.test.tsx (ui
 * side). The viewer is a full admin so every Can-gated control renders.
 *
 * Note: the team LIST renders through DataTable, which windows its rows via
 * @tanstack/react-virtual measuring the real scroll container height — jsdom
 * always reports 0, so no row text ever mounts in this environment (the same
 * is true of every other DataTable-backed screen in this codebase; see
 * DataTable.test.tsx, which only asserts the DOM row count stays bounded, not
 * that it is nonzero). These tests therefore drive selection through the
 * create-team flow (which sets `selected` directly, outside the table) rather
 * than clicking a table row, and verify the list request's variables instead
 * of its rendered text.
 */
let handler: (doc: string, vars: any) => any = () => ({});
const requests: { doc: string; vars: any }[] = [];
vi.mock("@/lib/graphql/client", async (importActual) => {
  const actual = await importActual<typeof import("@/lib/graphql/client")>();
  return {
    ...actual,
    graphqlRequest: (doc: string, vars: any) => {
      requests.push({ doc, vars });
      return Promise.resolve(handler(doc, vars));
    },
  };
});

import AdminTeamsPage from "./page";

const meResult = {
  me: { userId: "u-1", tenantId: "t-42", type: "user", scopes: [], roles: ["Admin"], capabilities: ["*"], capsDegraded: false },
};

const emptyGroupsPage = { groups: { nodes: [], pageInfo: { nextCursor: null, hasMore: false } } };

const membersResult = {
  groupMembers: [{ userId: "u-9", expiresAt: null, createdAt: "2026-01-02T00:00:00Z" }],
};

const rolesResult = {
  roles: {
    nodes: [{ id: "r-1", name: "Adjuster", system: true, version: 1, actions: ["case.case.read"], createdAt: null, updatedAt: null }],
    pageInfo: { nextCursor: null, hasMore: false },
  },
};

const groupRolesResult = {
  groupRoles: [{ id: "r-1", name: "Adjuster", system: true, version: 1, actions: ["case.case.read"], createdAt: null, updatedAt: null }],
};

beforeEach(() => {
  requests.length = 0;
  handler = (doc: string) => {
    if (doc.includes("query Me")) return meResult;
    if (doc.includes("query Groups")) return emptyGroupsPage;
    if (doc.includes("query GroupMembers")) return membersResult;
    if (doc.includes("query GroupRoles")) return groupRolesResult;
    if (doc.includes("query Roles")) return rolesResult;
    if (doc.includes("mutation CreateTeam")) {
      return { createTeam: { id: "g-new", urn: "wr:t:rbac:group/g-new", name: "New Team", description: null,
        groupType: "permission", system: false, autoGenerated: false, createdAt: null, updatedAt: null } };
    }
    if (doc.includes("mutation DeleteTeam")) return { deleteTeam: true };
    if (doc.includes("mutation AssignTeamRole")) return { assignTeamRole: true };
    if (doc.includes("mutation UnassignTeamRole")) return { unassignTeamRole: true };
    return {};
  };
});

async function createTeam(user: ReturnType<typeof userEvent.setup>) {
  await screen.findByText("No teams yet.");
  await user.click(screen.getByRole("button", { name: "New team" }));
  await user.type(screen.getByLabelText("Team name"), "New Team");
  await user.click(screen.getByRole("button", { name: "Create" }));
  expect(await screen.findByRole("heading", { name: "New Team" })).toBeInTheDocument();
}

describe("Admin Teams page", () => {
  it("requests the group list filtered to type=permission (Teams = permission-type rbac groups)", async () => {
    renderWithProviders(<AdminTeamsPage />);
    await waitFor(() => {
      const call = requests.find((r) => r.doc.includes("query Groups"));
      expect(call?.vars.type).toBe("permission");
    });
  });

  it("creates a team via createTeam and selects it", async () => {
    const user = userEvent.setup();
    renderWithProviders(<AdminTeamsPage />);
    await createTeam(user);

    const call = requests.find((r) => r.doc.includes("mutation CreateTeam"));
    expect(call?.vars.input).toMatchObject({ name: "New Team" });
  });

  it("selecting a team (via creation) shows its members and its currently-bound roles", async () => {
    const user = userEvent.setup();
    renderWithProviders(<AdminTeamsPage />);
    await createTeam(user);

    expect(await screen.findByText("u-9")).toBeInTheDocument();
    // The bound-roles list (rbac GET /groups/{id}/roles) renders each role's id.
    expect(await screen.findByText("r-1")).toBeInTheDocument();
    const membersCall = requests.find((r) => r.doc.includes("query GroupMembers"));
    expect(membersCall?.vars.groupId).toBe("g-new");
    const rolesCall = requests.find((r) => r.doc.includes("query GroupRoles"));
    expect(rolesCall?.vars.groupId).toBe("g-new");
  });

  it("binds a role to the selected team via assignTeamRole", async () => {
    const user = userEvent.setup();
    renderWithProviders(<AdminTeamsPage />);
    await createTeam(user);
    await screen.findByText("u-9");

    const select = await screen.findByLabelText("Role to bind");
    await user.selectOptions(select, "r-1");
    await user.click(screen.getByRole("button", { name: "Bind" }));

    await waitFor(() => {
      const call = requests.find((r) => r.doc.includes("mutation AssignTeamRole"));
      expect(call?.vars).toMatchObject({ groupId: "g-new", roleId: "r-1" });
    });
    expect(await screen.findByText(/Bound role r-1/)).toBeInTheDocument();
  });

  it("deletes the selected team through the confirm dialog and clears the selection", async () => {
    const user = userEvent.setup();
    renderWithProviders(<AdminTeamsPage />);
    await createTeam(user);

    await user.click(screen.getByRole("button", { name: "Delete" }));
    const dialog = await screen.findByRole("dialog");
    await user.click(within(dialog).getByRole("button", { name: "Delete" }));

    await waitFor(() => {
      expect(requests.some((r) => r.doc.includes("mutation DeleteTeam") && r.vars.id === "g-new")).toBe(true);
    });
    expect(await screen.findByText("Select a team to see its members and role bindings.")).toBeInTheDocument();
  });
});
