"use client";
import { useMemo, useState } from "react";
import { ShieldCheck, X } from "lucide-react";
import { PageHeader } from "@/components/shell/PageHeader";
import { DataTable, type Column } from "@/components/primitives/DataTable";
import { AsyncBoundary } from "@/components/primitives/AsyncBoundary";
import { Can } from "@/components/authz/Can";
import { Badge, Card, CardHeader, CardTitle, CardContent, Input } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";
import { FEATURE_GATES } from "@/lib/authz/registry";
import { useGroups, useGroupMembers, useAddGroupMember, useRemoveGroupMember } from "@/lib/graphql/hooks";
import type { Group } from "@/lib/graphql/types";
import { formatLocal } from "@/lib/utils";

export default function AdminGroupsPage() {
  const [type, setType] = useState("");
  const query = useGroups({ type: type || undefined });
  const rows = useMemo(() => query.data?.pages.flatMap((p) => p.nodes) ?? [], [query.data]);
  const [selected, setSelected] = useState<Group | null>(null);

  const columns: Column<Group>[] = [
    { id: "name", header: "Name", cell: (g) => <span className="font-medium">{g.name}</span> },
    { id: "type", header: "Type", width: 130, cell: (g) => <Badge variant="secondary">{g.groupType ?? "—"}</Badge> },
    {
      id: "kind", header: "Kind", width: 140,
      cell: (g) => g.system
        ? <Badge variant="warning">system</Badge>
        : g.autoGenerated ? <Badge variant="secondary">auto</Badge> : <Badge variant="success">custom</Badge>,
    },
    { id: "desc", header: "Description", cell: (g) => g.description || <span className="text-muted-foreground">—</span> },
  ];

  return (
    <div>
      <PageHeader
        title="Groups"
        description="Permission and content groups (rbac-service). Select a group to review its members."
      />

      <div className="mb-3 flex items-center gap-2">
        <label className="flex items-center gap-1 text-sm">
          <span className="text-muted-foreground">Type</span>
          <select value={type} onChange={(e) => setType(e.target.value)} aria-label="Filter by type"
            className="h-9 rounded-md border border-input bg-background px-2 text-sm">
            <option value="">all</option>
            <option value="permission">permission</option>
            <option value="content">content</option>
          </select>
        </label>
      </div>

      <div className="grid gap-4 lg:grid-cols-[1fr_360px]">
        <AsyncBoundary
          isLoading={query.isLoading}
          isError={query.isError}
          error={query.error}
          isEmpty={rows.length === 0}
          emptyTitle="No groups yet."
          onRetry={() => query.refetch()}
        >
          <DataTable
            ariaLabel="Groups"
            rows={rows}
            columns={columns}
            rowId={(g) => g.id}
            onRowActivate={(g) => setSelected(g)}
            hasMore={query.hasNextPage}
            isFetchingMore={query.isFetchingNextPage}
            onLoadMore={() => query.fetchNextPage()}
          />
        </AsyncBoundary>

        <MembersPanel group={selected} onClose={() => setSelected(null)} />
      </div>
    </div>
  );
}

function MembersPanel({ group, onClose }: { group: Group | null; onClose: () => void }) {
  const members = useGroupMembers(group?.id ?? null);
  const remove = useRemoveGroupMember(group?.id ?? "");
  const [addId, setAddId] = useState("");

  if (!group) {
    return (
      <Card className="h-fit">
        <CardHeader><CardTitle className="text-sm">Members</CardTitle></CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          <div className="flex flex-col items-center gap-2 py-6 text-center">
            <ShieldCheck className="size-6" aria-hidden />
            <p>Select a group to see its members.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="h-fit">
      <CardHeader className="flex-row items-center justify-between space-y-0">
        <CardTitle className="text-sm">Members · {group.name}</CardTitle>
        <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close"><X className="size-4" /></Button>
      </CardHeader>
      <CardContent className="space-y-3 text-sm">
        <AsyncBoundary
          isLoading={members.isLoading}
          isError={members.isError}
          error={members.error}
          isEmpty={(members.data?.length ?? 0) === 0}
          emptyTitle="No members in this group."
          onRetry={() => members.refetch()}
        >
          <ul className="space-y-1">
            {(members.data ?? []).map((m) => (
              <li key={m.userId} className="flex items-center justify-between gap-2 rounded-md border px-2 py-1.5">
                <div className="min-w-0">
                  <p className="truncate font-mono text-xs">{m.userId}</p>
                  <p className="text-xs text-muted-foreground">
                    joined {formatLocal(m.createdAt)}{m.expiresAt ? ` · expires ${formatLocal(m.expiresAt)}` : ""}
                  </p>
                </div>
                <Can gate={FEATURE_GATES.manageGroupMembers}>
                  <Button variant="ghost" size="sm" disabled={remove.isPending}
                    onClick={() => remove.mutate(m.userId)}>Remove</Button>
                </Can>
              </li>
            ))}
          </ul>
        </AsyncBoundary>

        <Can gate={FEATURE_GATES.manageGroupMembers}>
          <AddMember groupId={group.id} value={addId} setValue={setAddId} />
        </Can>
      </CardContent>
    </Card>
  );
}

function AddMember({ groupId, value, setValue }: { groupId: string; value: string; setValue: (v: string) => void }) {
  // Membership add is a clean idempotent PUT by user id; the caller supplies the
  // user id (copyable from the Users screen) to avoid guessing a directory search.
  const add = useAddGroupMember(groupId);
  return (
    <form
      className="flex items-center gap-2 border-t pt-3"
      onSubmit={(e) => { e.preventDefault(); if (value.trim()) add.mutate(value.trim(), { onSuccess: () => setValue("") }); }}
    >
      <Input value={value} onChange={(e) => setValue(e.target.value)} placeholder="user id to add" aria-label="User id to add" className="h-8 text-xs" />
      <Button type="submit" size="sm" disabled={!value.trim() || add.isPending}>Add</Button>
    </form>
  );
}
