// Package domain holds the core entities and pure business rules of
// rbac-service: workspaces, groups, roles, the action catalog, content-grant
// levels and URNs. It has no dependencies on storage, HTTP or Redis.
package domain

import (
	"time"

	"github.com/google/uuid"
)

// GroupType is the two-kind group model preserved from V1:
// permission groups carry roles; content groups carry workspace/data access.
type GroupType string

const (
	GroupTypePermission GroupType = "permission"
	GroupTypeContent    GroupType = "content"
)

func (t GroupType) Valid() bool {
	return t == GroupTypePermission || t == GroupTypeContent
}

// GrantLevel is the content-grant level lattice: viewer < editor < owner.
type GrantLevel string

const (
	LevelViewer GrantLevel = "viewer"
	LevelEditor GrantLevel = "editor"
	LevelOwner  GrantLevel = "owner"
)

func (l GrantLevel) Valid() bool {
	return l == LevelViewer || l == LevelEditor || l == LevelOwner
}

// SubjectType identifies who a content grant targets.
type SubjectType string

const (
	SubjectUser  SubjectType = "user"
	SubjectGroup SubjectType = "group"
)

// System role names — the V1 catalog, names preserved for migration
// (RBC-FR-020). "IDO User" was renamed to "Data User"; the old->new mapping
// ships in seed/roles_actions.yaml.
const (
	RoleAdmin           = "Admin"
	RoleUseCaseAdmin    = "Use case Admin"
	RoleDataUser        = "Data User"
	RoleModelBuilder    = "Model Builder"
	RoleDataIntegration = "Data Integration User"
	RoleInsights        = "Insights User"
	RoleInsightsAdHoc   = "Insights Ad-Hoc User"
	RoleCaseAnalyst     = "Case Analyst"
	RoleCaseManager     = "Case Manager"
	RoleCaseExecutive   = "Case Executive"
)

// SystemRoleNames lists the 10 system roles in seed order.
func SystemRoleNames() []string {
	return []string{
		RoleAdmin, RoleUseCaseAdmin, RoleDataUser, RoleModelBuilder,
		RoleDataIntegration, RoleInsights, RoleInsightsAdHoc,
		RoleCaseAnalyst, RoleCaseManager, RoleCaseExecutive,
	}
}

// DefaultWorkspaceName is the V1 name preserved for migration compatibility
// (RBC-FR-006).
const DefaultWorkspaceName = "Default use case"

type Workspace struct {
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Public      bool       `json:"public"`
	CreatedBy   string     `json:"created_by"`
	ArchivedAt  *time.Time `json:"archived_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

func (w Workspace) Archived() bool { return w.ArchivedAt != nil }

type Group struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Type          GroupType `json:"group_type"`
	System        bool      `json:"system"`
	AutoGenerated bool      `json:"auto_generated"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Member struct {
	GroupID   uuid.UUID  `json:"group_id"`
	UserID    string     `json:"user_id"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
}

type Role struct {
	ID        uuid.UUID  `json:"id"`
	TenantID  *uuid.UUID `json:"tenant_id,omitempty"` // nil = system role
	Name      string     `json:"name"`
	System    bool       `json:"system"`
	Version   int        `json:"version"`
	Actions   []string   `json:"actions,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type ContentGrant struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ResourceURN string      `json:"resource_urn"`
	SubjectType SubjectType `json:"subject_type"`
	SubjectID   string      `json:"subject_id"`
	Level       GrantLevel  `json:"level"`
	Implicit    bool        `json:"implicit"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

// Principal types carried in the JWT `typ` claim (MASTER-FR-011).
const (
	TypUser            = "user"
	TypService         = "service"
	TypAgentOBO        = "agent_obo"
	TypAgentAutonomous = "agent_autonomous"
)
