/**
 * TypeScript mirrors of the bff-graphql SDL (services/bff-graphql/src/schema/typeDefs.ts).
 * Hand-maintained (codegen requires a booted supergraph); the Playwright e2e runs
 * every operation against the REAL bff schema, which is the drift guard.
 */

export type ID = string;
export type JSONValue = any;

export type OperationStatus = "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
export type RunStatus = "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED";
export type CaseStatus = "DRAFT" | "UNASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED";
export type Severity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type ProposalStatus =
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "EDITED_APPROVED"
  | "RESPONDED"
  | "EXPIRED";
export type DecisionKind = "APPROVE" | "REJECT" | "EDIT_ARGS" | "RESPOND";

export interface PageInfo {
  nextCursor: string | null;
  hasMore: boolean;
}

export interface StreamHandle {
  hubUrl: string;
  topics: string[];
}

export interface CaseRowInput {
  rowPk: string;
  displayProjection: { key: string; value: string }[];
}

export interface CreateCasesInput {
  datasetUrn: string;
  datasetVersion?: string;
  queryUrn?: string;
  dashboardUrn?: string;
  dueDate: string;
  severity?: string;
  assignedToId?: string;
  description?: string;
  rows: CaseRowInput[];
}

export interface CreateCasesResult {
  createCases: {
    created: { id: string; caseNumber: number | null; status: string | null }[];
    deduplicated: { id: string; rowPk: string | null; caseNumber: number | null }[];
  };
}

export interface DatasetAggregateResult {
  datasetAggregate: {
    columns: string[];
    rows: (string | null)[][];
    sql: string;
  };
}

export interface DatasetRowPage {
  columns: string[];
  rows: (string | null)[][];
  total: number;
  filtered: number;
  offset: number;
  limit: number;
  /** True when the dataset exceeds the browse working-set cap; total/filtered
   * are lower bounds over the first N rows only. */
  truncated: boolean;
}

export interface DatasetRowsResult {
  datasetRows: DatasetRowPage;
}

export interface RowFilterInput {
  col: string;
  op: string;
  value: string;
}

export interface Viewer {
  userId: ID;
  tenantId: ID;
  /** Tenant display name (member-visible; null if the lookup failed). */
  tenantName: string | null;
  workspaceId: ID | null;
  workspaceName: string | null;
  type: string;
  scopes: string[];
  /** First-class cross-tenant platform operator (distinct from tenant Admin). */
  isPlatformAdmin: boolean;
  /** Role display names from rbac's projection (UI gate display data). */
  roles: string[];
  /** Allowed action names (e.g. "case.case.read"); "*" == tenant admin. */
  capabilities: string[];
  /** True when the rbac lookup FAILED and roles/capabilities are the fail-closed
   * empty fallback — show "permissions unavailable", not "you have no access". */
  capsDegraded: boolean;
  /** Per-tenant UI label overrides (BRD 23 inc3) the app overlays onto its base
   * i18n catalog to white-label the vertical (e.g. "Cases" -> "AP Exceptions"). */
  displayLabels?: LabelOverride[];
  /** The caller tenant's white-label brand (BRD 59 WS3). */
  branding?: TenantBranding;
}

// BRD 59 WS3: white-label branding. primaryColor/accentColor are bare HSL
// triplets ("221 83% 53%") applied directly as CSS custom properties; the
// logo bytes are fetched separately via /api/tenant-branding/logo.
export interface TenantBranding {
  configured: boolean;
  hasLogo: boolean;
  primaryColor: string;
  accentColor: string;
  updatedAt?: string | null;
}
export interface SetTenantBrandingInput {
  primaryColor: string;
  accentColor: string;
}

export interface LabelOverride {
  key: string;
  value: string;
}

export interface User {
  id: ID;
  urn: string;
  email: string;
  fullName?: string | null;
  status?: string | null;
  lastLoginAt?: string | null;
  createdAt?: string | null;
}

/* ---------- admin: rbac + identity + audit ---------- */
export interface Workspace {
  id: ID;
  urn: string;
  name: string;
  description?: string | null;
  public?: boolean | null;
  archived: boolean;
  archivedAt?: string | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface Group {
  id: ID;
  urn: string;
  name: string;
  description?: string | null;
  groupType?: string | null;
  system?: boolean | null;
  autoGenerated?: boolean | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface GroupMember {
  userId: ID;
  expiresAt?: string | null;
  createdAt?: string | null;
}

export interface CreateTeamInput {
  name: string;
  description?: string;
}

export interface UpdateTeamInput {
  name?: string;
  description?: string;
}

/** Edit a group's name/description (rbac PATCH /groups/{id}); group_type is immutable. */
export interface UpdateGroupInput {
  id: ID;
  name?: string;
  description?: string;
}

export interface Role {
  id: ID;
  name: string;
  system?: boolean | null;
  version?: number | null;
  actions: string[];
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface ServiceAccount {
  id: ID;
  urn: string;
  name: string;
  scopes: string[];
  expiresAt?: string | null;
  lastUsedAt?: string | null;
  revokedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

/* ---- Tier 4b: identity/rbac admin (lifecycle, roles, grants, bulk ops) ---- */
export interface UpdateWorkspaceInput {
  name?: string;
  description?: string;
  public?: boolean;
}

/** rbac's two-kind group model (wire value is lowercased by the BFF). */
export type GroupTypeInput = "PERMISSION" | "CONTENT";

export interface CreateGroupInput {
  name: string;
  description?: string;
  groupType: GroupTypeInput;
}

export interface GroupMemberOpInput {
  op: "ADD" | "REMOVE";
  userId: ID;
}

export interface GroupMemberOpResult {
  userId: ID;
  op: string;
  ok: boolean;
  code?: string | null;
}

/** The real per-entry partial-failure report of a bulk membership call. */
export interface BulkGroupMembershipResult {
  results: GroupMemberOpResult[];
  succeeded: number;
  failed: number;
}

export interface CreateRoleInput {
  name: string;
  actions: string[];
}

export interface UpdateRoleInput {
  name?: string;
  actions?: string[];
}

export interface CreateServiceAccountInput {
  name: string;
  scopes?: string[];
  expiresAt?: string;
}

/** A created/rotated service account WITH its one-time apiKey — shown exactly
 * once, never retrievable again, never persisted client-side. */
export interface CreatedServiceAccount {
  serviceAccount: ServiceAccount;
  apiKey: string;
}

/** One row of effective access to a resource (provenance direct |
 * implicit_creator | via_group; `via` names the group for via_group rows). */
export interface EffectiveAccessEntry {
  subjectType: string;
  subjectId: ID;
  level: string;
  provenance: string;
  via?: string | null;
  grantId: ID;
  workspaceId: ID;
}

export interface ContentGrant {
  id: ID;
  workspaceId: ID;
  resourceUrn: string;
  subjectType: string;
  subjectId: ID;
  level: string;
  implicit: boolean;
  createdAt?: string | null;
}

export interface CreateContentGrantInput {
  workspaceId: ID;
  resourceUrn: string;
  subjectType: "user" | "group";
  subjectId: ID;
  level: "viewer" | "editor" | "owner";
}

export interface TenantQuotas {
  cpu?: number | null;
  memory?: string | null;
  processingCpu?: number | null;
  processingMemory?: string | null;
}

export interface Tenant {
  id: ID;
  urn: string;
  name: string;
  displayName?: string | null;
  ownerEmail?: string | null;
  tier?: string | null;
  cloud?: string | null;
  status?: string | null;
  subdomain?: string | null;
  platformVersion?: string | null;
  autoUpgrade?: boolean | null;
  modules: string[];
  quotas?: TenantQuotas | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  embedConfig?: EmbedConfig | null;
}

/** A tenant's embedded-UI (iframe) configuration. The secret is never
 * readable after generation — only its presence (configured) is exposed. */
export interface EmbedConfig {
  configured: boolean;
  allowedOrigins: string[];
  updatedAt?: string | null;
}

/** PUT-equivalent response: embedSecret is shown exactly once, at
 * generation/rotation time — store it immediately, it can't be re-fetched. */
export interface SetEmbedConfigResult {
  embedSecret: string;
  allowedOrigins: string[];
}

/** BYO-P4: the caller tenant's own OIDC IdP (configured=false when SSO off). */
export interface TenantIdpConfig {
  configured: boolean;
  issuer?: string | null;
  clientId?: string | null;
  discoveryUrl?: string | null;
  enabled: boolean;
  updatedAt?: string | null;
}
export interface SetTenantIdpInput {
  issuer: string;
  clientId?: string;
  discoveryUrl?: string;
  enabled?: boolean;
}

// BRD 59 WS2: per-tenant SIEM export destination (four-eyes gated).
export interface SiemConfig {
  id: string;
  endpoint: string;
  format: "CEF" | "LEEF" | "JSON";
  active: boolean;
  status: string;
  requestedBy: string;
  approvedBy?: string | null;
  rejectedBy?: string | null;
  rejectReason?: string | null;
  createdAt: string;
  updatedAt: string;
}
export interface SiemConfigState {
  active: SiemConfig | null;
  pending: SiemConfig | null;
  history: SiemConfig[];
}
export interface ProposeSiemConfigInput {
  endpoint: string;
  format: "CEF" | "LEEF" | "JSON";
  authRef?: string;
}

export interface AuditEvent {
  eventId: ID;
  urn: string;
  eventType: string;
  tenantId?: ID | null;
  actorType?: string | null;
  actorId?: string | null;
  viaAgentId?: string | null;
  viaAgentVersion?: string | null;
  action?: string | null;
  resourceUrn?: string | null;
  occurredAt: string;
  ingestedAt?: string | null;
  traceId?: string | null;
  payloadDigest?: string | null;
  bodyWithheld?: boolean | null;
  payload?: JSONValue;
  chainSeq?: number | null;
  chainHash?: string | null;
}

export interface InviteUserInput {
  email: string;
  fullName?: string;
  groups?: string[];
}

export interface CreateWorkspaceInput {
  name: string;
  description?: string;
  public?: boolean;
}

export interface AuditEventsFilter {
  from?: string;
  to?: string;
  eventType?: string;
  action?: string;
  actorId?: string;
  actorType?: string;
  resourceUrn?: string;
}

export interface Profile {
  rowCount?: number | null;
  columnCount?: number | null;
  fullJsonUrl?: string | null;
  htmlReportUrl?: string | null;
}

export interface Dataset {
  id: ID;
  urn: string;
  name: string;
  description?: string | null;
  status?: string | null;
  tags: string[];
  rowCount?: number | null;
  createdAt?: string | null;
  archived: boolean;
  archivedAt?: string | null;
  profile?: Profile | null;
}

export interface LineageNode {
  urn: string;
  kind?: string | null;
  name?: string | null;
  status?: string | null;
}
export interface LineageEdge {
  fromUrn: string;
  toUrn: string;
  activity?: string | null;
  occurredAt?: string | null;
}
export interface DatasetLineage {
  nodes: LineageNode[];
  edges: LineageEdge[];
  truncated?: boolean | null;
}

/** Downstream-consumer rollup (dataset-service GET /datasets/{id}/consumers). */
export interface DatasetConsumers {
  downstreamEdges: number;
  byService: Record<string, number>;
  byActivity: Record<string, number>;
  truncated?: boolean | null;
}

/** A ranked similarity-search hit (dataset-service POST /datasets:similar). */
export interface SimilarDataset {
  id?: ID | null;
  urn?: string | null;
  name?: string | null;
  score?: number | null;
}

/** One immutable dataset version (dataset-service GET /datasets/{id}/versions). */
export interface DatasetVersion {
  id: ID;
  urn?: string | null;
  versionNo: number;
  icebergSnapshotId?: string | null;
  schema?: JSONValue;
  schemaDiff?: JSONValue;
  breakingChange?: boolean | null;
  rowCount?: number | null;
  bytes?: number | null;
  producedByUrn?: string | null;
  profileStatus?: string | null;
  expired?: boolean | null;
  createdAt?: string | null;
}

/** 202 ack from the manual re-profile trigger (async). */
export interface ReprofileResult {
  operationId?: ID | null;
  profileId?: ID | null;
  status?: string | null;
}

/** An ingestion run (ingestion-service). */
export interface Ingestion {
  id: ID;
  urn: string;
  mode: string;
  status: string;
  trigger?: string | null;
  connectionId?: ID | null;
  datasetUrn?: string | null;
  fileFormat?: string | null;
  statement?: string | null;
  rowsAppended?: number | null;
  bytesReceived?: number | null;
  bytesTotal?: number | null;
  attempts?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}
export interface CreateIngestionInput {
  mode: string;
  connectionId?: string;
  statement?: string;
  fileFormat?: string;
  datasetUrn?: string;
  newDatasetName?: string;
  newDatasetDescription?: string;
  skipProfiling?: boolean;
  allowEmpty?: boolean;
}

export interface UploadPart {
  n: number;
  etag: string;
  size: number;
}

/** A resumable chunked-upload session (ingestion-service). Chunk PUTs go
 * directly to /api/uploads/{uploadId}/parts/{n} (a ui-web API route), not
 * through GraphQL — see that route's doc comment. */
export interface Upload {
  uploadId: ID;
  ingestionId: ID;
  status?: string | null;
  partSize?: number | null;
  bytesTotal?: number | null;
  sha256?: string | null;
  expiresAt?: string | null;
  parts: UploadPart[];
}

export interface CreateUploadInput {
  ingestionId: string;
  partSize?: number;
  bytesTotal?: number;
}

export interface UploadPartInput {
  n: number;
  etag: string;
  size: number;
}

export interface CompleteUploadInput {
  parts: UploadPartInput[];
  sha256?: string;
}

/** A recurring ingestion schedule (ingestion-service /schedules). */
export interface IngestionSchedule {
  id: ID;
  urn: string;
  connectionId: ID;
  ingestionTemplate?: JSONValue;
  cron?: string | null;
  intervalSeconds?: number | null;
  timezone?: string | null;
  watermark?: JSONValue;
  overlapPolicy?: string | null;
  enabled: boolean;
  workspaceId?: string | null;
  lastFiredAt?: string | null;
  nextFireAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface ScheduleWatermarkInput {
  column: string;
  operator?: string;
  valueType?: string;
  initialValue: string;
}

/** Exactly ONE of cron / intervalSeconds (the service 422s otherwise). */
export interface CreateIngestionScheduleInput {
  connectionId: string;
  ingestionTemplate: JSONValue;
  cron?: string;
  intervalSeconds?: number;
  timezone?: string;
  watermark?: ScheduleWatermarkInput;
  overlapPolicy?: string;
  enabled?: boolean;
}

export interface UpdateIngestionScheduleInput {
  cron?: string;
  intervalSeconds?: number;
  timezone?: string;
  ingestionTemplate?: JSONValue;
  overlapPolicy?: string;
  enabled?: boolean;
}

export interface ScheduleRunNowResult {
  skipped: boolean;
  ingestionId?: ID | null;
  buffered?: boolean | null;
  status?: string | null;
}

/** A saved SQL query (query-service). */
export interface SavedQuery {
  id: ID;
  urn: string;
  name: string;
  description?: string | null;
  tags: string[];
  moduleNames: string[];
  sqlText?: string | null;
  variables?: JSONValue;
  versionNo?: number | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}
export interface QueryColumn {
  name: string;
  type?: string | null;
}
export interface QueryResult {
  executionId: ID;
  status: string;
  engine?: string | null;
  cacheHit?: boolean | null;
  durationMs?: number | null;
  resultRows?: number | null;
  scanBytes?: number | null;
  columns: QueryColumn[];
  /** Each row is a JSON array of scalar cells aligned to `columns`. */
  rows: JSONValue[];
  hasMore?: boolean | null;
  warnings?: JSONValue;
  error?: JSONValue;
}
export interface RunSqlInput {
  sql: string;
  limit?: number;
  engineHint?: string;
}

/** One immutable saved-query version (query-service). */
export interface SavedQueryVersion {
  id: ID;
  versionNo: number;
  sqlText?: string | null;
  variables?: JSONValue;
  datasetRefs?: JSONValue;
  createdBy?: string | null;
  createdAt?: string | null;
}

/** A query execution HISTORY row (no result rows — see QueryResult for those). */
export interface QueryExecution {
  id: ID;
  urn: string;
  status: string;
  engine?: string | null;
  cacheHit?: boolean | null;
  savedQueryId?: ID | null;
  queryVersionNo?: number | null;
  sqlText?: string | null;
  createdBy?: string | null;
  createdAt?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  durationMs?: number | null;
  resultRows?: number | null;
  scanBytes?: number | null;
  queuePosition?: number | null;
  error?: JSONValue;
}

export interface QueryStatRow {
  sqlFingerprint: string;
  executions: number;
  totalScanBytes: number;
  failures: number;
  topUser?: string | null;
}
export interface QueryStats {
  since?: string | null;
  topQueries: QueryStatRow[];
}

/** A typed variable declaration (query-service QRY-FR-002). */
export interface VariableDeclInput {
  name: string;
  type: string;
  required?: boolean;
  default?: JSONValue;
  allowedValues?: JSONValue[];
  min?: number;
  max?: number;
}

/** Create/update body for a saved query. Create requires name, moduleNames
 * (≥1) and sqlText server-side. */
export interface SavedQueryInput {
  name?: string;
  description?: string;
  sqlText?: string;
  variables?: VariableDeclInput[];
  tags?: string[];
  moduleNames?: string[];
}

export interface ChartData {
  rows?: JSONValue;
  columns?: JSONValue;
  /** Resolved artifact blob for the metric/parameter (dataset/run) family
   * (chart-service ShapedResult.artifact) — e.g.
   * {kind:"dataset_summary", metrics:[{label,value}]}. */
  artifact?: JSONValue;
  meta?: JSONValue;
}

export interface Chart {
  id: ID;
  urn: string;
  name?: string | null;
  chartType?: string | null;
  spec?: JSONValue;
  /** Editor config (chart-service `config`) — authoring round-trip. */
  config?: JSONValue;
  /** Editor display options (chart-service `display_meta`). */
  displayMeta?: JSONValue;
  /** Typed source references (chart-service `sources`). */
  sources?: JSONValue;
  data?: ChartData | null;
  provenance?: JSONValue;
}

export interface Dashboard {
  id: ID;
  urn: string;
  title: string;
  module?: string | null;
  archived: boolean;
  charts: Chart[];
}

/* ---------- charts: type catalog, semantic models, authoring (no-code editor) ---------- */

/** Config family from the chart-type catalog (chart-service). */
export type ChartFamily = "axis" | "y_only" | "heatmap" | "network" | "grid" | "metric";

/** One entry in the chart-type catalog (chart-service GET /chart-types). */
export interface ChartType {
  name: string;
  family: ChartFamily | string;
  dataClass?: string | null;
  requiredFields: string[];
  configSchema?: JSONValue;
}

/** A dimension in a semantic model's published definition (semantic-service). */
export interface SemanticDimension {
  name: string;
  entity?: string | null;
  dimType?: string | null;
}

/** A measure in a semantic model's published definition (semantic-service). */
export interface SemanticMeasure {
  name: string;
  agg?: string | null;
  entity?: string | null;
}

/** A semantic model + its published dimensions/measures. List items carry
 * empty dimensions/measures (headers only); semanticModel(name) hydrates them. */
export interface SemanticModel {
  id: ID;
  urn: string;
  name: string;
  dimensions: SemanticDimension[];
  measures: SemanticMeasure[];
}

/** Shaped data for an UNSAVED chart spec (chart-service POST /charts/preview). */
export interface ChartShapedData {
  chartId?: ID | null;
  chartType?: string | null;
  columns?: JSONValue;
  rows?: JSONValue;
  /** Resolved artifact blob for the metric/parameter (dataset/run) family
   * (chart-service ShapedResult.artifact). */
  artifact?: JSONValue;
  rowCount?: number | null;
  truncated?: boolean | null;
}

export interface ChartSourceInput {
  position: number;
  sourceType: string;
  sourceUrn: string;
}

export interface CreateChartInput {
  dashboardId: ID;
  name: string;
  chartType: string;
  description?: string;
  config: JSONValue;
  displayMeta?: JSONValue;
  sources?: ChartSourceInput[];
}

export interface UpdateChartInput {
  name?: string;
  chartType?: string;
  config?: JSONValue;
  displayMeta?: JSONValue;
  sources?: ChartSourceInput[];
}

export interface CreateDashboardInput {
  name: string;
  module?: string;
  description?: string;
  layout?: JSONValue;
  meta?: JSONValue;
  tags?: string[];
}

export interface UpdateDashboardInput {
  name?: string;
  description?: string;
  layout?: JSONValue;
  meta?: JSONValue;
  tags?: string[];
}

/** A scheduled dashboard-report email subscription (notification-service,
 * NOTIF-FR-060 — "Case Reports / Team Reports"). */
export interface ReportSubscription {
  id: ID;
  urn: string;
  dashboardId: ID;
  workspaceId: ID;
  name: string;
  recipients: string[];
  /** daily | weekly. */
  cadence: string;
  sendHour: number;
  sendWeekday?: number | null;
  timezone: string;
  /** html | text. */
  format: string;
  enabled: boolean;
  lastSentAt?: string | null;
  lastStatus?: string | null;
  lastError?: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateReportSubscriptionInput {
  dashboardId: ID;
  name: string;
  recipients: string[];
  cadence: string;
  sendHour?: number;
  sendWeekday?: number;
  timezone?: string;
  format?: string;
  enabled?: boolean;
}

export interface UpdateReportSubscriptionInput {
  name?: string;
  recipients?: string[];
  cadence?: string;
  sendHour?: number;
  sendWeekday?: number;
  timezone?: string;
  format?: string;
  enabled?: boolean;
}

export interface Proposal {
  id: ID;
  urn: string;
  agentKey?: string | null;
  tool?: string | null;
  argsDiff?: JSONValue;
  /**
   * Server-authoritative tool-plane risk tier (BFF passthrough):
   * read | write-proposal | write-direct | admin | "unknown". The UI fails
   * closed on anything outside the bulk-approvable allowlist.
   */
  riskTier?: string | null;
  rationale?: string | null;
  affectedUrns: string[];
  /**
   * Structured predicted-effect object from the originating agent
   * (agent-runtime always serializes Proposal.predicted_effect as a dict —
   * app/domain/entities.py). Always at least {summary, blast_radius,
   * reversibility}; some agents attach extra fields (e.g. `compatibility`).
   */
  predictedEffect?: { summary?: string | null; blast_radius?: number | null; reversibility?: string | null; [k: string]: unknown } | null;
  status?: ProposalStatus | null;
  decision?: JSONValue;
  createdAt?: string | null;
}

export interface TokenUsage {
  inputTokens?: number | null;
  outputTokens?: number | null;
}

export interface AgentRun {
  id: ID;
  urn: string;
  agentKey?: string | null;
  status?: RunStatus | null;
  costUsd?: number | null;
  tokenUsage?: TokenUsage | null;
  trace?: JSONValue;
  tokenStream: StreamHandle;
}

export interface RegisteredModel {
  id: ID;
  urn: string;
  name?: string | null;
  stage?: string | null;
}

export interface Run {
  id: ID;
  urn: string;
  name?: string | null;
  status?: RunStatus | null;
  metrics?: JSONValue;
  params?: JSONValue;
  model?: RegisteredModel | null;
  /** Tier 4b: the owning experiment (register-as-model needs both ids). */
  experimentId?: ID | null;
}

export interface Experiment {
  id: ID;
  urn: string;
  name: string;
  description?: string | null;
  archived: boolean;
  runs: Connection<Run>;
}

/* ---------- ml: model registry + inference jobs ---------- */
export interface ModelVersion {
  modelId: ID;
  version: number;
  urn: string;
  /** production | staging | archived | none */
  stage?: string | null;
  sourceRunId?: ID | null;
  flavor?: string | null;
  mlflowModelRef?: string | null;
  stageUpdatedAt?: string | null;
}

export interface Model {
  id: ID;
  urn: string;
  name?: string | null;
  modelType?: string | null;
  ownerId?: string | null;
  description?: string | null;
  createdAt?: string | null;
  /** Populated on the detail path only; [] on the list path. */
  versions: ModelVersion[];
}

export interface PromotionRequest {
  promotionId: ID;
  status: string;
  operationId?: string | null;
}

/** One promotion request against a model version (four-eyes approval queue). */
export interface Promotion {
  id: ID;
  urn: string;
  modelVersionId?: string | null;
  targetStage?: string | null;
  fromStage?: string | null;
  /** pending | approved | rejected | expired | cancelled */
  status?: string | null;
  rationale?: string | null;
  requestedBy?: string | null;
  viaAgent?: JSONValue | null;
  decision?: JSONValue | null;
  createdAt?: string | null;
}

export interface InferenceModelRef {
  urn?: string | null;
  name?: string | null;
  version?: number | null;
  stageAtSubmit?: string | null;
}

export interface InferenceDatasetRef {
  urn?: string | null;
  version?: number | null;
}

/** JobStatus name: validating | queued | submitted | running | finalizing |
 * succeeded | failed | cancelling | cancelled | rejected. */
export interface InferenceJob {
  id: ID;
  urn: string;
  name?: string | null;
  description?: string | null;
  status: string;
  model?: InferenceModelRef | null;
  inputDataset?: InferenceDatasetRef | null;
  outputDataset?: InferenceDatasetRef | null;
  rowCount?: number | null;
  error?: string | null;
  pipelineRunUrn?: string | null;
  scheduleId?: ID | null;
  /** Tier 4b: the job this one was retried FROM (set on the NEW job by retry). */
  retriedFromJobId?: ID | null;
  createdAt?: string | null;
  submittedAt?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
}

export interface CreateExperimentInput {
  name: string;
  modelType: string;
  description?: string;
  modelPipelineUrn: string;
  featureEngineeringPipelineUrn: string;
  trainingPipelineUrn: string;
}

export interface CreateInferenceJobInput {
  modelVersionUrn: string;
  inputDatasetUrn: string;
  name?: string;
  description?: string;
  allowUnpromoted?: boolean;
}

/* ---- Tier 4b: ml ops (register/notes/artifacts/compare/cards + inference ----
 * validate/schedules) --------------------------------------------------------- */

/** registerRunAsModel outcome (experiment-service register, 201). */
export interface RegisterModelResult {
  modelId: ID;
  version: number;
  /** Always "none" on a fresh registration. */
  stage?: string | null;
  modelCreated: boolean;
}

export interface RegisterRunInput {
  modelName: string;
  description?: string;
  flavor?: string;
  ownerId?: string;
}

/** PATCH /experiments/{id} — omitted fields stay unchanged. */
export interface UpdateExperimentInput {
  name?: string;
  description?: string;
  note?: string;
}

/** The free-text note on a run. */
export interface RunNote {
  runId: ID;
  description?: string | null;
}

/** One run artifact index row. */
export interface RunArtifact {
  path: string;
  sizeBytes?: number | null;
  contentType?: string | null;
}

/** One compare metric row (verbatim from experiment-service compare). */
export interface CompareMetricRow {
  key: string;
  values: Record<string, number | null>;
  best_run_id?: string | null;
  direction?: string;
}

/** One compare param row (verbatim). */
export interface CompareParamRow {
  key: string;
  values: Record<string, string | null>;
  differs?: boolean;
}

/** The server-side run comparison matrix. */
export interface RunComparison {
  runIds: ID[];
  metrics?: CompareMetricRow[] | null;
  params?: CompareParamRow[] | null;
}

/** One raw metric-history point (verbatim JSON rows). */
export interface MetricHistoryRow {
  key: string;
  step?: number | null;
  value?: number | null;
  logged_at?: string | null;
}

/** The 4 human-editable model-card overlay fields. */
export interface ModelCardOverlayInput {
  intendedUse?: string;
  limitations?: string;
  evaluationSummary?: string;
  ethicalConsiderations?: string;
}

/** One column verdict: ok | missing | type_mismatch | nullable_mismatch. */
export interface CompatColumn {
  name: string;
  requiredType?: string | null;
  actualType?: string | null;
  verdict: string;
}

/** The model×dataset compatibility report (inference-service validate). */
export interface InferenceCompatibilityReport {
  compatible: boolean;
  modelStage?: string | null;
  columns: CompatColumn[];
  warnings?: JSONValue;
  rowCount?: number | null;
  stageError?: string | null;
}

export interface ValidateInferenceInput {
  modelVersionUrn: string;
  inputDatasetUrn: string;
  allowUnpromoted?: boolean;
  allowEmpty?: boolean;
}

/** A recurring scoring schedule (inference-service /schedules). */
export interface InferenceSchedule {
  id: ID;
  urn: string;
  name?: string | null;
  enabled: boolean;
  pausedReason?: string | null;
  modelVersionUrn?: string | null;
  modelUrn?: string | null;
  /** production | staging | none | archived (fire-time resolution). */
  stageSelector?: string | null;
  /** {dataset_urn: "..."} — resolved fresh at each fire. */
  inputSelector?: JSONValue;
  /** {dataset_name, mode}. */
  output?: JSONValue;
  cron?: string | null;
  intervalSeconds?: number | null;
  timezone?: string | null;
  /** skip | queue | cancel_running. */
  overlapPolicy?: string | null;
  consecutiveFailures?: number | null;
  temporalScheduleId?: string | null;
  notifyOnFailure?: boolean | null;
  nextFireAt?: string | null;
}

/** Exactly ONE of modelVersionUrn / modelUrn (+stageSelector), and exactly ONE
 * of cron / intervalSeconds (the service 422s otherwise). */
export interface CreateInferenceScheduleInput {
  name: string;
  inputSelector: JSONValue;
  output: JSONValue;
  modelVersionUrn?: string;
  modelUrn?: string;
  stageSelector?: string;
  cron?: string;
  intervalSeconds?: number;
  timezone?: string;
  overlapPolicy?: string;
  enabled?: boolean;
  notifyOnFailure?: boolean;
}

/** ONLY these fields are PATCH-able (name/model/stage immutable; enabled flips
 * via pause/resume). */
export interface UpdateInferenceScheduleInput {
  cron?: string;
  intervalSeconds?: number;
  timezone?: string;
  overlapPolicy?: string;
  inputSelector?: JSONValue;
  output?: JSONValue;
  notifyOnFailure?: boolean;
}

export interface Case {
  id: ID;
  urn: string;
  caseNumber?: number | null;
  title?: string | null;
  status?: CaseStatus | null;
  severity?: Severity | null;
  dueDate?: string | null;
  createdAt?: string | null;
  assignee?: User | null;
  sourceDataset?: Dataset | null;
  proposals: Proposal[];
  /** Pack/dataset-provided evidence summary (key -> value; 'note' carries the
   * investigator briefing). Present on list rows AND detail. */
  displayProjection?: Record<string, string> | null;
  // Tier 4b: caseView detail fields (null on search-projection list rows).
  description?: string | null;
  dispositionId?: ID | null;
  resolutionNote?: string | null;
  resolvedAt?: string | null;
  closedAt?: string | null;
  caseVersion?: number | null;
  reassignCount?: number | null;
  /** Uploaded evidence attachments (task #77); resolved on the detail path. */
  evidence?: CaseEvidence[] | null;
}

/** One uploaded evidence file on a case (task #77). */
export interface CaseEvidence {
  id: ID;
  caseId: ID;
  filename: string;
  contentType: string;
  sizeBytes: number;
  uploadedBy?: string | null;
  createdAt?: string | null;
}

// ---- Tier 4b: case ops (case-service lifecycle/comments/export/catalog) ----

/** A case comment. The body is ONLY readable on the create response — the
 * backend has no list-comments route; the timeline carries comment ids. */
export interface CaseComment {
  id: ID;
  caseId?: ID | null;
  authorId?: string | null;
  author?: User | null;
  body?: string | null;
  editedAt?: string | null;
  createdAt?: string | null;
}

/** One case timeline entry (merged event+comment feed, newest-first). */
export interface CaseActivity {
  id: ID;
  caseId?: ID | null;
  eventType?: string | null;
  /** user | agent | system. */
  actorType?: string | null;
  actorId?: string | null;
  /** Hydrated only when actorType is "user". */
  actor?: User | null;
  viaAgent?: JSONValue;
  proposalUrn?: string | null;
  oldValue?: JSONValue;
  newValue?: JSONValue;
  occurredAt?: string | null;
}

/** An async case bulk/export operation (poll until succeeded|failed). */
export interface CaseOperation {
  id: ID;
  kind?: string | null;
  status?: string | null;
  succeeded?: number | null;
  failed?: number | null;
  total?: number | null;
  rowCount?: number | null;
  downloadUrl?: string | null;
  expiresAt?: string | null;
  error?: string | null;
}

export type DispositionCategory =
  | "true_positive"
  | "false_positive"
  | "benign"
  | "inconclusive"
  | "other";

/** A workspace disposition catalog entry — the vocabulary resolveCase uses. */
export interface Disposition {
  id: ID;
  urn: string;
  workspaceId?: ID | null;
  code?: string | null;
  label?: string | null;
  category?: DispositionCategory | null;
  requiresNote: boolean;
  active: boolean;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export type TriggerConditionOp = "eq" | "neq" | "contains" | "gt" | "gte" | "lt" | "lte";
export interface CaseTriggerCondition {
  col: string;
  op: TriggerConditionOp;
  value: string;
}
/** An event-rule case trigger (realtime-decisioning INC-1): ingestion
 * completes into the matching dataset → rows passing the conditions become
 * cases (idempotent via dataset_urn+row_pk dedup). */
export interface CaseTrigger {
  id: string;
  workspaceId: string | null;
  name: string;
  enabled: boolean;
  datasetUrn: string | null;
  datasetName: string | null;
  conditions: CaseTriggerCondition[];
  rowPkField: string | null;
  severity: string;
  dueHours: number;
  projectionFields: string[];
  maxCasesPerEvent: number;
  createdById: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}
export interface CaseTriggerInput {
  name?: string;
  enabled?: boolean;
  datasetUrn?: string;
  datasetName?: string;
  conditions?: CaseTriggerCondition[];
  rowPkField?: string;
  severity?: string;
  dueHours?: number;
  projectionFields?: string[];
  maxCasesPerEvent?: number;
}

export type CaseFieldDataType = "string" | "text" | "integer" | "float" | "boolean" | "date" | "enum";
export type CaseFieldPurpose = "create" | "update" | "both";

/** A custom case-field config (purpose normalized to its string form). */
export interface CaseField {
  id: ID;
  urn: string;
  workspaceId?: ID | null;
  queryUrn?: string | null;
  name?: string | null;
  dataType?: CaseFieldDataType | null;
  purpose?: CaseFieldPurpose | null;
  fieldMeta?: JSONValue;
  createdAt?: string | null;
  updatedAt?: string | null;
}

/** One embedded field def on a typed case schema (case-service inc10). */
export interface CaseSchemaField {
  name: string;
  dataType?: string | null;
  label?: string | null;
  required?: boolean | null;
}
/** A governed typed case SCHEMA — a named case TYPE binding a field set. */
export interface CaseSchema {
  id: ID;
  workspaceId?: ID | null;
  schemaKey: string;
  name: string;
  description?: string | null;
  fields: CaseSchemaField[];
  createdAt?: string | null;
  updatedAt?: string | null;
}

export type SlaOnBreach = "auto_unassign" | "escalate" | "notify_only";

/** The PUT /sla-policy echo. WRITE-ONLY: the backend has no read route. */
export interface CaseSlaPolicy {
  workspaceId?: ID | null;
  warnBeforeSeconds?: number | null;
  onBreach?: SlaOnBreach | null;
  maxReassignCount?: number | null;
}

export interface CreateDispositionInput {
  code: string;
  label: string;
  category: DispositionCategory;
  requiresNote?: boolean;
  active?: boolean;
}

export interface UpdateDispositionInput {
  label?: string;
  category?: DispositionCategory;
  /** Always send the intended value — the backend PATCH overwrites it unconditionally. */
  requiresNote?: boolean;
  active?: boolean;
}

export interface CreateCaseFieldInput {
  queryUrn?: string;
  name: string;
  dataType: CaseFieldDataType;
  purpose?: CaseFieldPurpose;
  fieldMeta?: JSONValue;
}

/** Edit a case field (case-service PATCH /case-fields/{id}); name/dataType are immutable. */
export interface UpdateCaseFieldInput {
  id: ID;
  purpose?: CaseFieldPurpose;
  fieldMeta?: JSONValue;
}

export interface CaseSlaPolicyInput {
  warnBeforeSeconds?: number;
  onBreach?: SlaOnBreach;
  escalateTo?: ID;
  maxReassignCount?: number;
}

export interface UsageRow {
  dimensions?: JSONValue;
  meterKey?: string | null;
  quantity?: number | null;
  costUsd?: number | null;
}

export interface BudgetState {
  scope?: string | null;
  consumed?: number | null;
  limit?: number | null;
  lastThreshold?: number | null;
  exhaustedAt?: string | null;
}

export interface CostPanel {
  rows: UsageRow[];
  budgetStates: BudgetState[];
}

export interface Budget {
  id: ID;
  urn: string;
  scope?: string | null;
  meterKey?: string | null;
  window?: string | null;
  limitUsd?: number | null;
  thresholds: number[];
  actionAt100?: string | null;
  status?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface CreateBudgetInput {
  workspaceId?: string;
  userId?: string;
  agentId?: string;
  meterKey: string;
  window: string;
  limitUsd: number;
  actionAt100?: string;
}

export interface UpdateBudgetInput {
  limitUsd?: number;
  actionAt100?: string;
}

export interface Anomaly {
  id: ID;
  urn: string;
  meterKey: string;
  day: string;
  observed: number;
  mean: number;
  stddev: number;
  z: number;
  /** open | dismissed */
  status: string;
  dismissedBy?: string | null;
  suppressedReason?: string | null;
  createdAt: string;
}

export interface RateCard {
  id: ID;
  urn: string;
  version?: number | null;
  effectiveFrom?: string | null;
  status?: string | null;
  items?: JSONValue;
  createdAt?: string | null;
}

export interface CreateRateCardInput {
  version: number;
  effectiveFrom: string;
  items: Record<string, number>;
}

export interface Connection<T> {
  nodes: T[];
  pageInfo: PageInfo;
}

/* ---------- ingestion: connector catalog + data-source connections ---------- */
export type ConnectorFieldType =
  | "string"
  | "integer"
  | "number"
  | "boolean"
  | "enum"
  | "object"
  | "array";

export interface ConnectorField {
  name: string;
  type: ConnectorFieldType;
  required: boolean;
  secret: boolean;
  default?: JSONValue;
  enum?: string[] | null;
  help?: string | null;
}

export type ConnectorCategory = "database" | "warehouse" | "object-store" | "file" | "saas";

export interface ConnectorType {
  connectorType: string;
  displayName: string;
  category: ConnectorCategory | string;
  fields: ConnectorField[];
  secretFields: string[];
  configSchema: JSONValue;
}

export interface DataConnection {
  id: ID;
  urn: string;
  name: string;
  connectorType: string;
  config: JSONValue;
  secretFields: string[];
  secretSet: boolean;
  trafficDirection?: string | null;
  tags: string[];
  workspaceId?: string | null;
  lastTestStatus?: string | null;
  lastTestedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export type ConnectionTestStatus = "OK" | "FAILED";

export interface ConnectionTestResult {
  status: ConnectionTestStatus;
  latencyMs?: number | null;
  errorCategory?: string | null;
  errorDetail?: string | null;
}

export interface CreateConnectionInput {
  name: string;
  type: string;
  config: JSONValue;
  secrets?: JSONValue;
  trafficDirection?: string;
  tags?: string[];
  workspaceId?: string;
  skipTest?: boolean;
}

/** A governed decision write-back job (ingestion-service, INS-FR-061).
 * status: pending_approval | delivering | delivered | failed | rejected. */
export interface Writeback {
  id: ID;
  urn: string;
  connectionId: ID;
  workspaceId?: string | null;
  decisionKind: string;
  decisionRef: string;
  target: JSONValue;
  payload: JSONValue;
  status: string;
  requestedBy: string;
  approvedBy?: string | null;
  attempts: number;
  lastError?: string | null;
  targetRef?: string | null;
  deliveredAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

// ---- BRD 54 inc2: governed decision tables ---------------------------------
export interface DecisionCondition { column: string; op: string; value?: JSONValue }
export interface DecisionOutcome { dispositionCode: string; severity: string }
export interface DecisionRule { when: DecisionCondition[]; then: DecisionOutcome | null; note?: string | null }
export interface DecisionModel {
  id: ID;
  name: string;
  version: number;
  status: string;
  workspaceId?: string | null;
  datasetUrn?: string | null;
  createdBy?: string | null;
  approvedBy?: string | null;
  approvedAt?: string | null;
  rules: DecisionRule[];
  defaultOutcome?: DecisionOutcome | null;
}
export interface CreateDecisionModelInput {
  name: string;
  workspaceId?: string;
  rules: Array<{ when: DecisionCondition[]; then: DecisionOutcome; note?: string }>;
  defaultOutcome?: DecisionOutcome | null;
}
export interface BatchEvaluateRow {
  caseId: ID;
  matched: boolean;
  ruleIndex: number | null;
  explanation: string;
  outcome: DecisionOutcome | null;
  proposalId?: string | null;
  proposalStatus?: string | null;
  executed?: boolean | null;
}
export interface BatchEvaluateResult {
  modelId: ID;
  proposed: boolean;
  summary: { cases: number; matched: number; unmatched: number; proposalsCreated: number; byOutcome: Record<string, number> };
  results: BatchEvaluateRow[];
}

// ---- BRD 56: entity resolution (steward surface) ---------------------------
export interface ResolutionRun {
  runId: ID;
  datasetId: ID;
  configId?: string | null;
  entityType: string;
  recordCount: number;
  resolvedEntityCount: number;
  mergedClusterCount: number;
  reviewCandidateCount: number;
  status: string;
  createdBy?: string | null;
  createdAt?: string | null;
}
export interface ResolvedMember { memberPk: string; method?: string | null; evidence?: JSONValue }
export interface ResolvedCluster {
  resolvedEntityId: ID;
  memberCount: number;
  confidence?: number | null;
  method?: string | null;
  members: ResolvedMember[];
}
export interface ResolutionRunDetail extends ResolutionRun {
  clusters: ResolvedCluster[];
}
export interface ResolveEntitiesResult {
  datasetId: ID;
  entityType: string;
  recordCount: number;
  resolvedEntityCount: number;
  mergedClusterCount: number;
  reviewCandidateCount: number;
  runId?: string | null;
  configId?: string | null;
  configVersion?: number | null;
}
export interface MergeCandidate {
  id: ID;
  runId: ID;
  datasetId: ID;
  entityType: string;
  leftPk: string;
  rightPk: string;
  score?: number | null;
  evidence?: JSONValue;
  status: string;
  proposalId?: string | null;
  decidedBy?: string | null;
  decidedAt?: string | null;
  createdAt?: string | null;
}
export interface EntityMergeProposal {
  proposalId: ID;
  status: string;
  executed?: boolean | null;
  runId?: string | null;
}
export interface MaterializeResolvedResult {
  resolvedDatasetId: ID;
  resolvedDatasetUrn: string;
  name: string;
  rowCount: number;
  columns: string[];
  versionNo: number;
  icebergTable: string;
}
export interface ScoringFieldInput { column: string; weight?: number }
export interface ResolutionConfigInput {
  entityType?: string;
  deterministicKeys?: string[][];
  scoringFields?: ScoringFieldInput[];
  blockingFields?: string[];
  autoMergeThreshold?: number;
  reviewThreshold?: number;
}
export interface ResolveEntitiesInput {
  pkColumn: string;
  config: ResolutionConfigInput;
  rowLimit?: number;
}
export interface ProposeEntityMergeInput {
  datasetId: string;
  runId: string;
  candidateId: string;
  leftPk?: string;
  rightPk?: string;
  score?: number;
  workspaceId?: string;
  rationale?: string;
}
export interface MaterializeAttributeInput { column: string; agg?: string }
export interface MaterializeResolvedInput {
  name?: string;
  workspaceId?: string;
  attributes: MaterializeAttributeInput[];
}

// ---- BRD 23: capability packs (pack-service) -------------------------------
export interface PackComponentCount { kind: string; count: number }
export interface PackDeferred { kind: string; reason: string }
export interface Pack {
  name: string;
  version: string;
  description: string;
  publisherName?: string | null;
  categories: string[];
  regulatory: string[];
  components: PackComponentCount[];
  deferredKinds: string[];
  deferred?: PackDeferred[];
}
export interface PackPlanOp {
  kind: string;
  identity: string;
  name?: string | null;
  action: string;
  detail?: string | null;
}
export interface PackLedgerRow {
  id: string;
  kind: string;
  identity: string;
  targetUrn?: string | null;
  targetId?: string | null;
  origin: string;
  action: string;
  detail?: string | null;
  reversible: boolean;
  tombstoned: boolean;
}
export interface PackInstall {
  id: string;
  pack: string;
  version: string;
  workspaceId: string;
  status: string;
  summary?: Record<string, number> | null;
  createdBy?: string | null;
  createdAt?: string | null;
  plan?: PackPlanOp[];
  ledger?: PackLedgerRow[];
}
export interface PackInstallPlan {
  pack: string;
  version: string;
  workspaceId: string;
  plan: PackPlanOp[];
}
export interface PackUninstallResult {
  id: string;
  status: string;
  reversed: number;
  tombstoned: number;
}
export interface PackCompleteResult {
  id: string;
  status: string;
  dashboards: PackLedgerRow[];
}
export interface PackDrift {
  id: string;
  pack: string;
  version: string;
  workspaceId: string;
  superseded: boolean;
  drifted: number;
  inSync: boolean;
  summary: Record<string, number>;
  objects: Record<string, unknown>[];
}
export interface PackTransitionDiff {
  added: number;
  removed: number;
  retained: number;
}
export interface PackTransition {
  id: string | null;
  pack: string;
  operation: string;
  fromVersion: string | null;
  toVersion: string | null;
  dryRun: boolean;
  status: string | null;
  supersedes: string | null;
  summary: Record<string, unknown> | null;
  diff: PackTransitionDiff;
}

export interface CreateWritebackInput {
  connectionId: string;
  decisionKind: string;
  decisionRef: string;
  target?: JSONValue;
  payload?: JSONValue;
  workspaceId?: string;
}

/** Edit a saved connection. Secrets are write-only and MERGE server-side:
 * supplied keys overwrite the Vault values, omitted keys are preserved. */
export interface UpdateConnectionInput {
  name?: string;
  config?: JSONValue;
  secrets?: JSONValue;
  trafficDirection?: string;
  tags?: string[];
  skipTest?: boolean;
}

/** Sample-rows request against a saved connection (exactly one of table/path/query). */
export interface ConnectionPreviewInput {
  table?: string;
  path?: string;
  query?: string;
  limit?: number;
}

/** ≤100 live rows from the source (never persisted). */
export interface ConnectionPreview {
  columns: string[];
  rows: JSONValue[];
}

/* ---------- pipelines: step catalog, templates, runs (no-code builder) ---------- */
export type PipelineParamType =
  | "string"
  | "integer"
  // Backend canonical name for a whole number (catalog `_TYPES` uses `int`, not
  // `integer`); rendered + validated identically to `integer`.
  | "int"
  | "number"
  | "boolean"
  | "enum"
  | "object"
  // Backend canonical name for a JSON object with non-string values (e.g. numeric
  // weights) — distinct from the `key_value` str→str map; edited as raw JSON like
  // `object`.
  | "dictionary"
  | "array"
  // A reference to a workspace dataset (URN string). Rendered as a dataset
  // picker in the builder; validated as a non-empty string like `string`.
  | "dataset_ref";

/** A single configurable parameter of a pipeline step (mirrors ConnectorField
 * but with `enumValues` + numeric `min`/`max` and no `secret`). */
export interface PipelineStepParam {
  name: string;
  type: PipelineParamType;
  required: boolean;
  default?: JSONValue;
  enumValues?: string[] | null;
  min?: number | null;
  max?: number | null;
  help?: string | null;
  /**
   * Semantic hint (JSON-Schema `format`) that drives the widget + data-binding,
   * independent of `type` (the storage shape). E.g. a `columns` format on an
   * `array`-typed param renders a data-aware column multi-select. Unknown/absent
   * formats degrade to the base `type` widget (forward-compatible).
   */
  format?: string | null;
  /** Element `format` for `array`-typed params (e.g. an array of `column`s). */
  itemFormat?: string | null;
}

/** Port type that flows along an edge between two step nodes. */
export type PortType = "dataframe" | "model" | "metrics" | "json" | "dataset_ref";

export interface PipelinePort {
  name: string;
  type: PortType | string;
}

export type PipelineStepCategory = "io" | "data_prep" | "algorithm" | "utility";

/** A step type from the bff catalog: the building block of the DAG. */
export interface PipelineStepType {
  name: string;
  displayName: string;
  category: PipelineStepCategory | string;
  description?: string | null;
  minInputs: number;
  maxInputs: number;
  maxOutputs: number;
  outputs: PipelinePort[];
  parameters: PipelineStepParam[];
}

/** A tunable algorithm (surfaced alongside step types in the palette). */
export interface AlgorithmTemplate {
  name: string;
  displayName: string;
  family: string;
  modes: string[];
  parameters: PipelineStepParam[];
}

/** The serialized DAG we POST as `definition`. */
export interface PipelineDefNode {
  alias: string;
  component: string;
  parameters: Record<string, unknown>;
  outputs: PipelinePort[];
}
export interface PipelineDefEdge {
  from: string; // "alias.port"
  to: string; // "alias.port"
  type: PortType | string;
}
export interface PipelineDefinition {
  nodes: PipelineDefNode[];
  edges: PipelineDefEdge[];
}

export interface PipelineTemplate {
  id: ID;
  urn: string;
  name: string;
  pipelineType: string;
  activeVersionId?: string | null;
  definition?: PipelineDefinition | JSONValue;
  validationStatus?: string | null;
  /** System-owned templates cannot be archived (409). */
  isSystem?: boolean | null;
  /** Soft-deleted; restorePipelineTemplate undoes it. */
  archived?: boolean | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface PipelineRun {
  id: ID;
  urn: string;
  templateId: string;
  status?: RunStatus | string | null;
  error?: JSONValue;
  retriedFromRunId?: ID | null;
  createdAt?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
}

/** A recurring pipeline schedule (pipeline-orchestrator /pipeline-schedules). */
export interface PipelineSchedule {
  id: ID;
  urn: string;
  scheduleId: ID;
  templateId: ID;
  name?: string | null;
  cron: string;
  timezone?: string | null;
  runParameters?: JSONValue;
  enabled: boolean;
  nextFireAt?: string | null;
  lastFireAt?: string | null;
  lastRunId?: ID | null;
  createdAt?: string | null;
}

export interface CreatePipelineScheduleInput {
  templateId: string;
  name?: string;
  cron: string;
  timezone?: string;
  runParameters?: JSONValue;
}

/** One immutable pipeline-template version (pipeline-orchestrator). */
export interface PipelineTemplateVersion {
  id: ID;
  templateId: ID;
  versionNo: number;
  validationStatus?: string | null;
  validationReport?: JSONValue;
  manifestDigest?: string | null;
  argoTemplateName?: string | null;
  createdAt?: string | null;
}

/** POST /pipelines/{id}/compile result. */
export interface CompiledPipelineManifest {
  templateId?: ID | null;
  versionId?: ID | null;
  manifestDigest?: string | null;
  argoTemplateName?: string | null;
  manifest?: JSONValue;
}

/** GET /runs/{id}/manifest result. */
export interface PipelineRunManifest {
  runId?: ID | null;
  manifest?: JSONValue;
  resolvedParameters?: JSONValue;
}

export interface ValidationIssue {
  code: string;
  message: string;
  node?: string | null;
}
export interface ValidationResult {
  valid: boolean;
  issues: ValidationIssue[];
}

export interface CreatePipelineInput {
  name: string;
  pipelineType: string;
  definition: PipelineDefinition | JSONValue;
}
/** Edit an existing template: type is immutable, so only name + definition. */
export interface UpdatePipelineInput {
  name: string;
  definition: PipelineDefinition | JSONValue;
}
export interface RunPipelineInput {
  parameters?: JSONValue;
}

export interface DatasetFilter {
  status?: string;
  tags?: string;
}
export interface CaseFilter {
  status?: string;
  severity?: string;
  assignee?: string;
}
export interface CasePatchInput {
  description?: string;
  dueDate?: string;
  severity?: Severity;
  customFields?: JSONValue;
}
export interface DecisionInput {
  kind: DecisionKind;
  reason?: string;
  editedArgs?: JSONValue;
  responseText?: string;
}

/* ---------- semantic model authoring (semantic-service) --------------------- */
export interface DatasetColumn {
  name: string;
  type?: string | null;
  nullable?: boolean | null;
  tags: string[];
  /** True when sourced from profiling rather than the dataset version's
   * authoritative schema (which is empty for some older-ingested datasets). */
  inferred: boolean;
}

export type SemanticVersionStatus = "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "REJECTED" | "SUPERSEDED";

export interface SemanticModelSummary {
  id: ID;
  urn: string;
  workspaceId?: string | null;
  name: string;
  description?: string | null;
  publishedVersionNo?: number | null;
  draftVersionNo?: number | null;
  healthStatus?: string | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface SemanticEntity {
  name: string;
  datasetUrn: string;
  table: string;
  primaryKey: string[];
  datasetVersionPolicy: JSONValue;
  description?: string | null;
}

export interface SemanticDimensionDef {
  name: string;
  entity: string;
  column?: string | null;
  expr?: string | null;
  dimType: string;
  timeGrains: string[];
  synonyms: string[];
  description?: string | null;
  deprecated: boolean;
  successor?: string | null;
}

export interface SemanticMeasureDef {
  name: string;
  entity?: string | null;
  agg?: string | null;
  expr?: string | null;
  exprMetric?: string | null;
  filters?: string | null;
  format?: string | null;
  synonyms: string[];
  description?: string | null;
  deprecated: boolean;
  successor?: string | null;
}

export interface SemanticJoinPathOn {
  fromColumn: string;
  toColumn: string;
}
export interface SemanticJoinPath {
  name: string;
  fromEntity: string;
  toEntity: string;
  joinType: string;
  on: SemanticJoinPathOn[];
  cardinality: string;
}

export interface SemanticModelDefinition {
  entities: SemanticEntity[];
  dimensions: SemanticDimensionDef[];
  measures: SemanticMeasureDef[];
  joinPaths: SemanticJoinPath[];
}

/** The raw JSON document shape the editor builds/round-trips (snake_case,
 * mirrors semantic-service's `definition` document exactly). */
export interface SemanticDefinitionDoc {
  entities: {
    name: string;
    dataset_urn: string;
    table: string;
    primary_key: string[];
    dataset_version_policy: { policy: "latest" | "pinned"; version_no?: number };
    description?: string;
  }[];
  dimensions: {
    name: string;
    entity: string;
    column?: string;
    expr?: string;
    type: string;
    time_grains?: string[];
    synonyms?: string[];
    description?: string;
    deprecated?: boolean;
    successor?: string;
  }[];
  measures: {
    name: string;
    entity?: string;
    agg?: string;
    expr?: string;
    expr_metric?: string;
    filters?: string;
    format?: string;
    synonyms?: string[];
    description?: string;
    deprecated?: boolean;
    successor?: string;
  }[];
  join_paths: {
    name: string;
    from_entity: string;
    to_entity: string;
    join_type: string;
    on: { from_column: string; to_column: string }[];
    cardinality: string;
  }[];
}

export interface SemanticModelVersion {
  id: ID;
  urn: string;
  modelId: ID;
  versionNo: number;
  status: SemanticVersionStatus;
  definition?: SemanticModelDefinition | null;
  definitionJson?: SemanticDefinitionDoc | JSONValue | null;
  diff?: JSONValue;
  submittedBy?: string | null;
  approvedBy?: string | null;
  decisionNote?: string | null;
  publishedAt?: string | null;
  createdAt?: string | null;
}

export interface CreateSemanticModelInput {
  name: string;
  description?: string;
  definition?: JSONValue;
}
export interface UpdateSemanticModelInput {
  name?: string;
  description?: string;
}

export interface SemanticDimensionRefInput {
  name: string;
  grain?: string;
}
export interface SemanticFilterInput {
  dimension: string;
  op: string;
  values?: JSONValue[];
}
export interface CompileSemanticModelInput {
  model: string;
  workspaceId?: string;
  metrics: string[];
  dimensions?: SemanticDimensionRefInput[];
  filters?: SemanticFilterInput[];
  limit?: number;
  dialect?: string;
  draftVersionNo?: number;
  validate?: boolean;
}

export interface SemanticOutputColumn {
  name: string;
  type?: string | null;
  role?: string | null;
}
export interface SemanticCompileResult {
  sql: string;
  engineDialect?: string | null;
  outputSchema: SemanticOutputColumn[];
  warnings: string[];
  provenance?: JSONValue;
  validationAvailable: boolean;
  validationValid?: boolean | null;
  validationMessage?: string | null;
}

export type VerifiedQueryStatus = "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "REJECTED" | "ARCHIVED";

/** A verified NL↔SQL pair (semantic-service, four-eyes governance). */
export interface VerifiedQuery {
  id: ID;
  urn: string;
  workspaceId?: ID | null;
  modelId?: ID | null;
  nlText: string;
  sqlText: string;
  variables?: JSONValue;
  status: VerifiedQueryStatus;
  tags: string[];
  provenance?: JSONValue;
  healthNote?: string | null;
  submittedBy?: string | null;
  approvedBy?: string | null;
  decidedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

/** One hit from semantic search over APPROVED pairs (SEM-FR-041). */
export interface VerifiedQuerySearchHit {
  id: ID;
  nlText: string;
  sqlText: string;
  variables?: JSONValue;
  tags: string[];
  modelId?: ID | null;
  score: number;
}

export interface CreateVerifiedQueryInput {
  nlText: string;
  sqlText: string;
  variables?: JSONValue;
  model?: string;
  tags?: string[];
}

export interface UpdateVerifiedQueryInput {
  nlText?: string;
  sqlText?: string;
  variables?: JSONValue;
  tags?: string[];
}

/** An async semantic-service operation (bootstrap-from-dataset), pollable. */
export interface SemanticOperation {
  operationId: ID;
  kind?: string | null;
  status?: string | null;
  report?: JSONValue;
  createdAt?: string | null;
  finishedAt?: string | null;
}

// ---- kill switches (agent-runtime + tool-plane, ART-FR-073 / TPL-FR-052) ----
export type KillSwitchTarget = "AGENT" | "TOOL";

export interface KillSwitch {
  id: ID;
  target: KillSwitchTarget;
  scope: string;
  agentKey?: string | null;
  toolId?: string | null;
  version?: string | null;
  tenantId?: string | null;
  active: boolean;
  reason: string;
  setBy: string;
  createdAt?: string | null;
}

export interface KillSwitchLiftResult {
  id: ID;
  active: boolean;
}

// ---- memory (memory-service, MEM-FR-010/011/020/040/050/051/052) -----------
export interface MemoryRecord {
  id: ID;
  urn: string;
  /** session | user | workspace | tenant */
  scope: string;
  scopeRef: string;
  /** UNTRUSTED model input (BR-12) — render as plain text, never execute. */
  content: string;
  confidence?: number | null;
  /** active | quarantined | expired | deleted */
  status: string;
  tags: string[];
  provenance?: JSONValue | null;
  retrievalCount?: number | null;
  classifierScore?: number | null;
  ttlExpiresAt?: string | null;
  mergedFrom?: string[] | null;
  revalidateAt?: string | null;
}

export interface ErasureRequest {
  operationId: ID;
  /** received | running | verifying | completed | failed */
  status: string;
  report?: JSONValue | null;
  completedAt?: string | null;
}

// ---- rbac authz explain (debug "why was I denied") -------------------------
export interface AuthzChainStep {
  type: string;
  group?: string | null;
  groupType?: string | null;
  role?: string | null;
  action?: string | null;
  workspaceScoped?: boolean | null;
  viaGroup?: string | null;
  workspace?: string | null;
  level?: string | null;
  subject?: string | null;
  admin?: boolean | null;
  detail?: string | null;
}

export interface AuthzExplanation {
  allowed: boolean;
  reason: string;
  chain: AuthzChainStep[];
}

export interface ExplainAuthzInput {
  userId: string;
  typ?: string;
  scopes?: string[];
  action: string;
  resourceUrn?: string;
  workspaceId?: string;
}

// ---- audit compliance packs + chain-integrity verify ------------------------
export interface ChainVerifyResult {
  valid: boolean;
  eventsChecked: number;
  chainHead: string;
  manifestMatch: boolean;
  firstMismatchSeq?: number | null;
  sealed: boolean;
}

export interface ComplianceJob {
  operationId: ID;
  /** running | succeeded | failed */
  status: string;
  resultUrl?: string | null;
  error?: string | null;
}

// ===========================================================================
// Tier 2a: eval (eval-service) — eval flywheel: suites/runs/gates/canaries.
// ===========================================================================
export interface EvalSuite {
  id: ID;
  urn: string;
  suiteId: string;
  agentKey: string;
  version: number;
  datasets: JSONValue;
  scorers: JSONValue;
  gateRule: string;
  baselineVersion?: string | null;
  judgeLadderPin?: JSONValue;
  minCases: number;
  createdAt?: string | null;
}

export interface EvalCaseResult {
  id: ID;
  runId: ID;
  caseId: ID;
  scorerKey: string;
  scorerVersion: number;
  score: number;
  passed: boolean;
  details?: JSONValue;
  traceRef?: string | null;
  latencyMs?: number | null;
  costUsd: number;
  weight: number;
  createdAt?: string | null;
}

export interface EvalGateResult {
  id: ID;
  urn: string;
  gateRunId: string;
  runId: ID;
  agentKey: string;
  contentDigest: string;
  suiteId: string;
  suiteVersion: number;
  datasetVersion: number;
  gatePassed: boolean;
  verdicts: JSONValue;
  failedCasesSample?: JSONValue;
  reportUrl?: string | null;
  createdAt?: string | null;
}

export interface EvalRun {
  id: ID;
  urn: string;
  trigger: string;
  agentKey: string;
  candidate: JSONValue;
  baseline?: JSONValue | null;
  suitePins: JSONValue;
  memorySnapshotVer?: string | null;
  /** queued | running | scoring | completed | failed */
  status: string;
  totals: JSONValue;
  costUsd: number;
  costCapUsd: number;
  startedBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  cases?: EvalCaseResult[];
  suite?: EvalSuite | null;
  gate?: EvalGateResult | null;
}

export interface EvalDataset {
  id: ID;
  urn: string;
  datasetKey: string;
  agentKey: string;
  version: number;
  /** draft | frozen | archived */
  status: string;
  description?: string | null;
  caseCount: number;
  provenanceSummary?: JSONValue;
  frozenBy?: string | null;
  frozenAt?: string | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface EvalCase {
  id: ID;
  urn: string;
  datasetKey: string;
  datasetVersion: number;
  input: JSONValue;
  expected: JSONValue;
  source: string;
  sourceRef?: string | null;
  tags: string[];
  weight: number;
  /** candidate | active | retired */
  status: string;
  anonymizationAttestedBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface EvalScorer {
  id: ID;
  urn: string;
  scorerKey: string;
  version: number;
  /** deterministic | llm_judge */
  kind: string;
  gateEligible: boolean;
  configSchema?: JSONValue;
  applicableExpectedKinds: string[];
  imageRef?: string | null;
  judgePromptRef?: string | null;
  judgePromptVer?: string | null;
  judgeAgreement?: number | null;
  status: string;
  createdAt?: string | null;
}

export interface EvalCanary {
  id: ID;
  urn: string;
  comparisonId: string;
  agentKey: string;
  candidateVersion: string;
  baselineVersion: string;
  sampleSpec?: JSONValue;
  mode: string;
  /** collecting | ready | failed_early | expired */
  status: string;
  report: JSONValue;
  samples: number;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface EvalTrendPoint {
  runId: ID;
  agentVersion?: string | null;
  scorer: string;
  mean?: number | null;
  passRate?: number | null;
  at: string;
}

export interface EvalSloRow {
  agentKey: string;
  agentVersion?: string | null;
  tenantId?: string | null;
  window: string;
  windowStart: string;
  metrics: JSONValue;
  targets: JSONValue;
  sampleN: number;
}

export interface CreateEvalSuiteInput {
  suiteId: string;
  agentKey: string;
  datasets: JSONValue;
  scorers: JSONValue;
  gateRule: string;
  baselineVersion?: string;
  judgeLadderPin?: JSONValue;
  minCases?: number;
}

/** Edit a suite (eval-service PATCH /suites); suiteId + agentKey are immutable. */
export interface UpdateEvalSuiteInput {
  suiteId: string;
  version?: number;
  datasets?: JSONValue;
  scorers?: JSONValue;
  gateRule?: string;
  baselineVersion?: string;
  judgeLadderPin?: JSONValue;
  minCases?: number;
}

export interface CreateEvalRunInput {
  trigger?: string;
  agentKey: string;
  candidate: JSONValue;
  suiteId: string;
  suiteVersion?: number;
  candidateOutputs?: JSONValue;
  baseline?: JSONValue;
  memorySnapshotVer?: string;
  costCapUsd?: number;
}

export interface CreateEvalDatasetInput {
  datasetKey: string;
  agentKey: string;
  description?: string;
  provenanceSummary?: JSONValue;
}

export interface CreateEvalCaseInput {
  datasetKey: string;
  agentKey?: string;
  input: JSONValue;
  expected: JSONValue;
  source?: string;
  sourceRef?: string;
  tags?: string[];
  weight?: number;
  status?: string;
  anonymizationAttestedBy?: string;
}

export interface EvalCasePatchInput {
  input?: JSONValue;
  expected?: JSONValue;
  tags?: string[];
  weight?: number;
  anonymizationAttestedBy?: string;
}

export interface CreateEvalScorerInput {
  scorerKey: string;
  version: number;
  kind: string;
  gateEligible?: boolean;
  configSchema?: JSONValue;
  applicableExpectedKinds?: string[];
  imageRef?: string;
  judgePromptRef?: string;
  judgePromptVer?: string;
  judgeAgreement?: number;
  status?: string;
}

/** Edit a scorer (eval-service PATCH /scorers); scorerKey + kind are immutable. */
export interface UpdateEvalScorerInput {
  scorerKey: string;
  version?: number;
  gateEligible?: boolean;
  configSchema?: JSONValue;
  applicableExpectedKinds?: string[];
  imageRef?: string;
  judgePromptRef?: string;
  judgePromptVer?: string;
  judgeAgreement?: number;
  status?: string;
}

export interface CreateEvalCanaryInput {
  agentKey: string;
  candidateVersion: string;
  baselineVersion: string;
  mode?: string;
  sampleSpec?: JSONValue;
  thresholds?: JSONValue;
  mustScorers?: string[];
}

// ===========================================================================
// Tier 2a: ai-gateway admin — provider catalog, routing ladders, ai-gateway's
// OWN LLM-spend budgets (distinct from Budget/BudgetState above), virtual
// keys, guardrail policy.
// ===========================================================================
export interface AiProviderDeployment {
  id: ID;
  provider: string;
  modelFamily: string;
  deploymentName: string;
  region: string;
  cloud: string;
  endpointVaultRef: string;
  tpmLimit: number;
  rpmLimit: number;
  priority: number;
  /** active | draining | disabled */
  status: string;
  circuitState?: string | null;
  healthy?: boolean | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface AiModelLadder {
  id: ID;
  requestClass: string;
  scope: string;
  rungs: JSONValue;
  version: number;
  maxRung?: number | null;
}

export interface AiBudget {
  id: ID;
  urn: string;
  /** platform | tenant | workspace | principal | virtual_key */
  scopeType: string;
  scopeRef: string;
  /** daily | monthly */
  window: string;
  limitUsd: number;
  degradePct: number;
  status: string;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface AiSpendRow {
  budgetId: ID;
  scopeType: string;
  scopeRef: string;
  window: string;
  windowStart: string;
  limitUsd: number;
  spendUsd: number;
  reservedUsd: number;
  resetAt: string;
}

// ADDED (provider-agnostic + cost-detail): per-provider/model cost breakdown.
export interface AiCostRollup {
  provider?: string | null;
  model?: string | null;
  modelAlias?: string | null;
  requestClass?: string | null;
  requests: number;
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
}

export interface AiCostBreakdown {
  window: { since: string; hours: number; priceVersion: string };
  totals: { requests: number; inputTokens: number; outputTokens: number; costUsd: number };
  byProvider: AiCostRollup[];
  byModel: AiCostRollup[];
  byRequestClass: AiCostRollup[];
  detail: AiCostRollup[];
}

export interface AiVirtualKey {
  id: ID;
  urn: string;
  principalType: string;
  principalId: string;
  allowedRequestClasses?: string[] | null;
  maxRung: number;
  expiresAt?: string | null;
  status: string;
  createdAt?: string | null;
  /** Only present on the create/rotate response (shown once, AIG-FR-030). */
  secret?: string | null;
}

export interface AiGuardrailPolicy {
  policy: JSONValue;
  version: number;
}

export interface CreateAiProviderInput {
  provider: string;
  modelFamily: string;
  deploymentName: string;
  region: string;
  cloud: string;
  endpointVaultRef: string;
  tpmLimit?: number;
  rpmLimit?: number;
  priority?: number;
}

export interface PatchAiProviderInput {
  status?: string;
  priority?: number;
  tpmLimit?: number;
  rpmLimit?: number;
  endpointVaultRef?: string;
  reason?: string;
}

export interface CreateAiBudgetInput {
  scopeType: string;
  scopeRef: string;
  window: string;
  limitUsd: number;
  degradePct?: number;
}

export interface PatchAiBudgetInput {
  limitUsd?: number;
  degradePct?: number;
  status?: string;
}

export interface CreateAiVirtualKeyInput {
  principalType: string;
  principalId: string;
  allowedRequestClasses?: string[];
  maxRung?: number;
  ttlSeconds?: number;
}

// ============================================================================
// Tier 2b: notification-service — inbox, preferences, rules, webhooks,
// templates, admin delivery stats + suppressions.
// ============================================================================
export interface Notification {
  id: ID;
  urn: string;
  eventType: string;
  severityClass?: string | null;
  title: string;
  body?: string | null;
  resourceUrn?: string | null;
  deepLink?: string | null;
  readAt?: string | null;
  createdAt?: string | null;
}

export interface NotificationPreferences {
  /** event_type -> channels */
  channelOverrides: Record<string, string[]>;
  mutes?: { event_types?: string[]; resource_urns?: string[] } | null;
  quietHours?: { tz: string; start: string; end: string } | null;
  /** event_class -> digest window */
  digestConfig: Record<string, string>;
  updatedAt?: string | null;
}

export interface NotificationRule {
  id: ID;
  scope: string;
  subjectType: string;
  subjectId: string;
  eventTypes: string[];
  resourceFilter?: JSONValue;
  channels: string[];
  digestEnabled: boolean;
  digestWindow?: string | null;
  active: boolean;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface WebhookSecret {
  version: number;
  /** Only selected on the create/rotate mutation responses (shown-once UX);
   * the list/update selections deliberately omit it. */
  secret?: string;
  createdAt?: string | null;
  expiresAt?: string | null;
}

export interface WebhookEndpoint {
  id: ID;
  url: string;
  eventTypes: string[];
  secrets: WebhookSecret[];
  active: boolean;
  verifiedAt?: string | null;
  circuitState?: string | null;
  consecutiveFailures?: number | null;
  createdBy?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface WebhookDelivery {
  id: ID;
  eventId?: ID | null;
  status: string;
  attempts: number;
  lastError?: string | null;
  providerMsgId?: string | null;
  nextRetryAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface NotificationTemplate {
  id: ID;
  key: string;
  channel: string;
  locale: string;
  version: number;
  subjectTpl?: string | null;
  bodyHtmlTpl?: string | null;
  bodyTextTpl?: string | null;
  status: string;
  publishedAt?: string | null;
  createdBy?: string | null;
  createdAt?: string | null;
}

export interface NotificationTemplatePreview {
  subject: string;
  html: string;
  text: string;
}

export interface NotificationDeliveryStats {
  window: string;
  byChannel: JSONValue;
}

export interface EmailSuppression {
  id: ID;
  emailHash: string;
  reason: string;
  createdAt?: string | null;
  clearedAt?: string | null;
}

// ============================================================================
// Tier 2b: tool-plane registry admin — catalog, lifecycle, enablement, BYO.
// ============================================================================
export interface Tool {
  toolId: ID;
  displayName?: string | null;
  ownerService: string;
  ownerTeam?: string | null;
  enabledByDefault: boolean;
  sideEffects: string;
  tags: string[];
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface ToolVersion {
  toolId: ID;
  version: string;
  status: string;
  semanticDescription?: string | null;
  permissionTier?: string | null;
  costWeight?: number | null;
  sideEffects?: string | null;
  inputSchema?: JSONValue;
  outputSchema?: JSONValue;
  declaredSla?: JSONValue;
  deprecationEndsAt?: string | null;
  publishedAt?: string | null;
}

export interface ToolVersionLifecycleResult {
  status: string;
  deprecationEndsAt?: string | null;
}

export interface ToolVersionHealth {
  version: string;
  status: string;
  declaredSla?: JSONValue;
  health?: JSONValue;
}

export interface ToolHealth {
  toolId: ID;
  versions: ToolVersionHealth[];
}

export interface ToolSchema {
  toolId: ID;
  version: string;
  inputSchema?: JSONValue;
  outputSchema?: JSONValue;
}

export interface TenantToolSettings {
  toolId: ID;
  enabled: boolean;
  maxTierOverride?: string | null;
  argumentConstraints?: JSONValue;
  rateLimitOverride?: JSONValue;
  updatedAt?: string | null;
}

export interface ByoSubmission {
  id: ID;
  manifest?: JSONValue;
  endpointUrl: string;
  authMethod: string;
  requestedTier: string;
  egressDescription?: string | null;
  status: string;
  decidedBy?: string | null;
  decisionMessage?: string | null;
  createdAt?: string | null;
}

export interface ByoDecision {
  id: ID;
  status: string;
  decidedBy: string;
}

// ============================================================================
// Tier 2b: agent-runtime catalog/registry — definitions, versions, tenant
// config, run history.
// ============================================================================
export interface AgentDefinition {
  agentKey: ID;
  displayName: string;
  description?: string | null;
  ownerTeam?: string | null;
  defaultWriteMode?: string | null;
  status?: string | null;
  latestPublishedVersion?: number | null;
}

export interface AgentVersionInfo {
  agentKey: ID;
  version: number;
  status: string;
  graphRef?: string | null;
  graphDigest?: string | null;
  guardrailProfile?: string | null;
  evalGateResultId?: string | null;
  toolset?: JSONValue;
  modelConfig?: JSONValue;
}

export interface AgentVersionPublishResult {
  agentKey: ID;
  version: number;
  status: string;
}

export interface TenantAgentConfig {
  agentKey: ID;
  configured: boolean;
  enabled: boolean;
  pinnedVersion?: number | null;
  promptParams?: JSONValue;
  autoExecutePolicy?: JSONValue;
  selfApproval: boolean;
}

export interface AgentRunListItem {
  id: ID;
  urn: string;
  sessionId?: ID | null;
  agentKey?: string | null;
  agentVersion?: number | null;
  /** Uppercased passthrough (NOT the RunStatus enum): agent runs carry extra
   * states like AWAITING_APPROVAL while a proposal is pending. */
  status?: string | null;
  principalType?: string | null;
  usage?: JSONValue;
  error?: JSONValue;
  createdAt?: string | null;
}
