package store

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/windrose-ai/rbac-service/internal/domain"
	"github.com/windrose-ai/rbac-service/internal/events"
)

const groupCols = `id, tenant_id, name, description, group_type, system, auto_generated, created_at, updated_at`

func scanGroup(row pgx.Row) (domain.Group, error) {
	var g domain.Group
	err := row.Scan(&g.ID, &g.TenantID, &g.Name, &g.Description, &g.Type, &g.System, &g.AutoGenerated, &g.CreatedAt, &g.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return g, ErrNotFound
	}
	return g, err
}

func (s *Store) getGroupTx(ctx context.Context, tx pgx.Tx, id uuid.UUID) (domain.Group, error) {
	return scanGroup(tx.QueryRow(ctx, `SELECT `+groupCols+` FROM groups WHERE id = $1`, id))
}

// CreateGroup implements RBC-FR-010 (unique name per tenant per type).
func (s *Store) CreateGroup(ctx context.Context, op Op, name, description string, gtype domain.GroupType, autoGenerated bool) (domain.Group, error) {
	name = strings.TrimSpace(name)
	if name == "" || !gtype.Valid() {
		return domain.Group{}, &ValidationError{Code: CodeValidationFailed, Message: "name and group_type (permission|content) are required"}
	}
	var g domain.Group
	err := s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		var err error
		g, err = scanGroup(tx.QueryRow(ctx, `
			INSERT INTO groups (id, tenant_id, name, description, group_type, system, auto_generated)
			VALUES ($1,$2,$3,$4,$5,false,$6) RETURNING `+groupCols,
			NewID(), op.Tenant, name, description, gtype, autoGenerated))
		if err != nil {
			if isUniqueViolation(err) {
				return &ConflictError{Code: CodeConflict, Message: fmt.Sprintf("%s group %q already exists in tenant", gtype, name)}
			}
			return err
		}
		return op.emit(ctx, tx, events.EvGroupCreated, groupURN(op.Tenant, g.ID),
			map[string]any{"name": g.Name, "group_type": string(g.Type)})
	})
	return g, err
}

// GetGroup fetches one group (RLS hides other tenants' rows -> 404).
func (s *Store) GetGroup(ctx context.Context, tenant uuid.UUID, id uuid.UUID) (domain.Group, error) {
	var g domain.Group
	err := s.WithTenant(ctx, tenant, func(tx pgx.Tx) error {
		var err error
		g, err = s.getGroupTx(ctx, tx, id)
		return err
	})
	return g, err
}

// ListGroups filters by type; auto-generated service groups are hidden unless
// includeAuto (RBC-FR-014, admin API only).
func (s *Store) ListGroups(ctx context.Context, tenant uuid.UUID, gtype domain.GroupType, includeAuto bool, cursor string, limit int) (Page[domain.Group], error) {
	limit = ClampLimit(limit)
	var page Page[domain.Group]
	where := []string{"true"}
	args := []any{}
	n := 1
	if gtype != "" {
		if !gtype.Valid() {
			return page, &ValidationError{Code: CodeValidationFailed, Message: "type must be permission|content"}
		}
		where = append(where, fmt.Sprintf("group_type = $%d", n))
		args = append(args, gtype)
		n++
	}
	if !includeAuto {
		where = append(where, "NOT auto_generated")
	}
	if cursor != "" {
		cid, err := uuid.Parse(cursor)
		if err != nil {
			return page, &ValidationError{Code: CodeValidationFailed, Message: "invalid cursor"}
		}
		where = append(where, fmt.Sprintf("id > $%d", n))
		args = append(args, cid)
		n++
	}
	args = append(args, limit+1)
	q := `SELECT ` + groupCols + ` FROM groups WHERE ` + strings.Join(where, " AND ") + fmt.Sprintf(` ORDER BY id LIMIT $%d`, n)

	err := s.WithTenant(ctx, tenant, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, q, args...)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			g, err := scanGroup(rows)
			if err != nil {
				return err
			}
			page.Data = append(page.Data, g)
		}
		return rows.Err()
	})
	if err != nil {
		return page, err
	}
	if len(page.Data) > limit {
		page.Data = page.Data[:limit]
		page.HasMore = true
		page.NextCursor = page.Data[limit-1].ID.String()
	}
	return page, nil
}

// UpdateGroup renames/re-describes; system groups are immutable (RBC-FR-013).
func (s *Store) UpdateGroup(ctx context.Context, op Op, id uuid.UUID, name, description *string) (domain.Group, error) {
	var g domain.Group
	err := s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		cur, err := s.getGroupTx(ctx, tx, id)
		if err != nil {
			return err
		}
		if cur.System && name != nil {
			return &ConflictError{Code: CodeSystemImmutable, Message: "system groups cannot be renamed"}
		}
		newName, newDesc := cur.Name, cur.Description
		if name != nil {
			newName = strings.TrimSpace(*name)
			if newName == "" {
				return &ValidationError{Code: CodeValidationFailed, Message: "name must not be empty"}
			}
		}
		if description != nil {
			newDesc = *description
		}
		g, err = scanGroup(tx.QueryRow(ctx, `
			UPDATE groups SET name=$2, description=$3, updated_at=now() WHERE id=$1 RETURNING `+groupCols,
			id, newName, newDesc))
		if err != nil {
			if isUniqueViolation(err) {
				return &ConflictError{Code: CodeConflict, Message: fmt.Sprintf("group %q already exists in tenant", newName)}
			}
			return err
		}
		return op.emit(ctx, tx, events.EvGroupUpdated, groupURN(op.Tenant, id), map[string]any{"name": g.Name})
	})
	return g, err
}

// DeleteGroup cascades workspace links AND content grants atomically via FKs
// (RBC-FR-012, BR-2 — fixes V1's orphaned-ACL defect) and recomputes members.
func (s *Store) DeleteGroup(ctx context.Context, op Op, id uuid.UUID) error {
	return s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		g, err := s.getGroupTx(ctx, tx, id)
		if err != nil {
			return err
		}
		if g.System {
			return &ConflictError{Code: CodeSystemImmutable, Message: "system groups cannot be deleted"}
		}
		// Mark members dirty before the cascade removes membership rows.
		if err := markDirtyGroupMembers(ctx, tx, op.Tenant, id, "group.deleted"); err != nil {
			return err
		}
		if _, err := tx.Exec(ctx, `DELETE FROM groups WHERE id = $1`, id); err != nil {
			return err
		}
		return op.emit(ctx, tx, events.EvGroupDeleted, groupURN(op.Tenant, id),
			map[string]any{"name": g.Name, "group_type": string(g.Type)})
	})
}

// AddMember is idempotent (AC-9): duplicate adds are a no-op success and
// exactly one membership row exists (RBC-FR-011 unique pair).
func (s *Store) AddMember(ctx context.Context, op Op, groupID uuid.UUID, userID string, expiresAt *string) (created bool, err error) {
	err = s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		if _, err := s.getGroupTx(ctx, tx, groupID); err != nil {
			return err
		}
		tag, err := tx.Exec(ctx, `
			INSERT INTO members (id, tenant_id, group_id, user_id, expires_at)
			VALUES ($1,$2,$3,$4,$5::timestamptz)
			ON CONFLICT (group_id, user_id) DO NOTHING`,
			NewID(), op.Tenant, groupID, userID, expiresAt)
		if err != nil {
			return err
		}
		if tag.RowsAffected() == 0 {
			return nil // idempotent no-op
		}
		created = true
		if err := markDirtyUsers(ctx, tx, op.Tenant, []string{userID}, "member.added"); err != nil {
			return err
		}
		return op.emit(ctx, tx, events.EvMemberAdded, groupURN(op.Tenant, groupID),
			map[string]any{"user_id": userID, "group_id": groupID.String()})
	})
	return created, err
}

// GrantOwnerAdmin adds userID as a member of the tenant's system "Admin"
// permission group — the tenant-provisioning owner bootstrap (BR-7): the
// SeedDefaults workflow step invites the tenant owner for real (Keycloak
// user + User row + invitation), and SeedTenant (consumed from
// tenant.provisioned) creates the tenant's system permission groups
// including Admin, but nothing previously added the owner AS A MEMBER of
// that group — so a freshly-provisioned tenant's owner could complete their
// invitation, log in for real, and see an EMPTY /me/capabilities (only
// Home+Copilot nav). Consumed from identity.events.v1 user.invited when the
// payload carries is_owner=true (set only for the bootstrap invite, never
// for a regular admin-driven POST /users invite).
//
// MUST NOT assume the Admin group already exists: identity.events.v1 has a
// single partition, and the provisioning workflow emits user.invited (from
// the SeedDefaults step) BEFORE tenant.provisioned (emitted only once ALL
// steps, including the later Verify step, succeed) — so an ordered consumer
// processes user.invited strictly first. Requiring the group to pre-exist
// deadlocks: this handler would exhaust its retries and DLQ while the very
// message that creates the group (tenant.provisioned -> SeedTenant) sits
// queued behind it in the same partition, unprocessed. SeedTenant is cheap
// and idempotent, so call it here to guarantee the group exists regardless
// of delivery order (live-reproduced: without this, EVERY fresh tenant hit
// "no Admin permission group" until tenant.provisioned's retries separately
// resolved it seconds later on the NEXT event, and even then this handler's
// own message had already gone to DLQ and was never retried).
//
// Idempotent (AC-9): mirrors AddMember's ON CONFLICT DO NOTHING + dirty-mark
// + event-emit shape, but resolves the group by name since the caller has
// no group id.
func (s *Store) GrantOwnerAdmin(ctx context.Context, op Op, userID string) (created bool, err error) {
	if err := s.SeedTenant(ctx, op); err != nil {
		return false, fmt.Errorf("ensure tenant seeded before owner grant: %w", err)
	}
	err = s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		var groupID uuid.UUID
		if err := tx.QueryRow(ctx,
			`SELECT id FROM groups WHERE tenant_id = $1 AND group_type = 'permission' AND lower(name) = lower('Admin')`,
			op.Tenant).Scan(&groupID); err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				return fmt.Errorf("tenant %s has no Admin permission group after SeedTenant: %w",
					op.Tenant, err)
			}
			return err
		}
		tag, err := tx.Exec(ctx, `
			INSERT INTO members (id, tenant_id, group_id, user_id)
			VALUES ($1,$2,$3,$4)
			ON CONFLICT (group_id, user_id) DO NOTHING`,
			NewID(), op.Tenant, groupID, userID)
		if err != nil {
			return err
		}
		if tag.RowsAffected() == 0 {
			return nil // idempotent no-op: owner already granted (e.g. event replay)
		}
		created = true
		if err := markDirtyUsers(ctx, tx, op.Tenant, []string{userID}, "owner.admin_granted"); err != nil {
			return err
		}
		return op.emit(ctx, tx, events.EvMemberAdded, groupURN(op.Tenant, groupID),
			map[string]any{"user_id": userID, "group_id": groupID.String(), "reason": "tenant_owner_bootstrap"})
	})
	return created, err
}

// AssignUserToGroups adds a user to one or more permission groups, identified
// by group id (uuid) or name (case-insensitive) within the tenant. Used to
// honour the initial groups on a user invite (IDN-FR-021), so an invited user
// arrives with a role instead of zero permissions. Best-effort per group: an
// unknown or non-permission group is skipped (never fails the whole invite /
// DLQs the consumer). Idempotent (ON CONFLICT DO NOTHING); marks the user dirty
// so the perm projection reflects the new membership.
func (s *Store) AssignUserToGroups(ctx context.Context, op Op, userID string, groups []string) error {
	if userID == "" || len(groups) == 0 {
		return nil
	}
	return s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		added := false
		for _, ref := range groups {
			ref = strings.TrimSpace(ref)
			if ref == "" {
				continue
			}
			var groupID uuid.UUID
			var qerr error
			if gid, perr := uuid.Parse(ref); perr == nil {
				qerr = tx.QueryRow(ctx,
					`SELECT id FROM groups WHERE tenant_id = $1 AND group_type = 'permission' AND id = $2`,
					op.Tenant, gid).Scan(&groupID)
			} else {
				qerr = tx.QueryRow(ctx,
					`SELECT id FROM groups WHERE tenant_id = $1 AND group_type = 'permission' AND lower(name) = lower($2)`,
					op.Tenant, ref).Scan(&groupID)
			}
			if errors.Is(qerr, pgx.ErrNoRows) {
				continue // unknown / non-permission group — skip, don't fail
			}
			if qerr != nil {
				return qerr
			}
			tag, err := tx.Exec(ctx, `
				INSERT INTO members (id, tenant_id, group_id, user_id)
				VALUES ($1,$2,$3,$4)
				ON CONFLICT (group_id, user_id) DO NOTHING`,
				NewID(), op.Tenant, groupID, userID)
			if err != nil {
				return err
			}
			if tag.RowsAffected() == 0 {
				continue // already a member (event replay) — idempotent
			}
			added = true
			if err := op.emit(ctx, tx, events.EvMemberAdded, groupURN(op.Tenant, groupID),
				map[string]any{"user_id": userID, "group_id": groupID.String(), "reason": "invite_initial_groups"}); err != nil {
				return err
			}
		}
		if added {
			return markDirtyUsers(ctx, tx, op.Tenant, []string{userID}, "invite.initial_groups")
		}
		return nil
	})
}

// RemoveMember enforces last-admin protection (RBC-FR-015/AC-6): removing the
// last member of the tenant-admin permission group is rejected 409 LAST_ADMIN
// unless a super-admin override with a reason is supplied (audited).
func (s *Store) RemoveMember(ctx context.Context, op Op, groupID uuid.UUID, userID string, overrideReason string, superAdmin bool) error {
	return s.WithTenant(ctx, op.Tenant, func(tx pgx.Tx) error {
		g, err := s.getGroupTx(ctx, tx, groupID)
		if err != nil {
			return err
		}
		if g.System && g.Type == domain.GroupTypePermission && g.Name == domain.RoleAdmin {
			var count int
			if err := tx.QueryRow(ctx, `SELECT count(*) FROM members WHERE group_id = $1`, groupID).Scan(&count); err != nil {
				return err
			}
			if count <= 1 {
				if !(superAdmin && overrideReason != "") {
					return &ConflictError{Code: CodeLastAdmin, Message: "cannot remove the last member of the tenant admin group"}
				}
				if err := op.emit(ctx, tx, events.EvLastAdminOverridden, groupURN(op.Tenant, groupID),
					map[string]any{"user_id": userID, "reason": overrideReason}); err != nil {
					return err
				}
			}
		}
		tag, err := tx.Exec(ctx, `DELETE FROM members WHERE group_id=$1 AND user_id=$2`, groupID, userID)
		if err != nil {
			return err
		}
		if tag.RowsAffected() == 0 {
			return ErrNotFound
		}
		if err := markDirtyUsers(ctx, tx, op.Tenant, []string{userID}, "member.removed"); err != nil {
			return err
		}
		return op.emit(ctx, tx, events.EvMemberRemoved, groupURN(op.Tenant, groupID),
			map[string]any{"user_id": userID, "group_id": groupID.String()})
	})
}

// BulkMemberOp is one entry of a bulk membership call (RBC-FR-016).
type BulkMemberOp struct {
	Op     string `json:"op"` // add | remove
	UserID string `json:"user_id"`
}

// BulkMemberResult reports per-entry outcome (partial failure allowed).
type BulkMemberResult struct {
	UserID string `json:"user_id"`
	Op     string `json:"op"`
	OK     bool   `json:"ok"`
	Code   string `json:"code,omitempty"`
}

// MaxBulkMembers caps bulk membership calls (RBC-FR-016).
const MaxBulkMembers = 500

// BulkMembers applies up to 500 add/remove ops with a partial-failure report.
// Each op commits independently so one bad entry doesn't poison the batch.
func (s *Store) BulkMembers(ctx context.Context, op Op, groupID uuid.UUID, ops []BulkMemberOp) ([]BulkMemberResult, error) {
	if len(ops) == 0 || len(ops) > MaxBulkMembers {
		return nil, &ValidationError{Code: CodeValidationFailed, Message: fmt.Sprintf("between 1 and %d operations per call", MaxBulkMembers)}
	}
	results := make([]BulkMemberResult, 0, len(ops))
	for _, o := range ops {
		res := BulkMemberResult{UserID: o.UserID, Op: o.Op}
		var err error
		switch o.Op {
		case "add":
			_, err = s.AddMember(ctx, op, groupID, o.UserID, nil)
		case "remove":
			err = s.RemoveMember(ctx, op, groupID, o.UserID, "", false)
			if errors.Is(err, ErrNotFound) {
				err = nil // removing a non-member is a no-op
			}
		default:
			err = &ValidationError{Code: CodeValidationFailed, Message: "op must be add|remove"}
		}
		if err != nil {
			res.Code = errCode(err)
		} else {
			res.OK = true
		}
		results = append(results, res)
	}
	return results, nil
}

func errCode(err error) string {
	var ce *ConflictError
	if errors.As(err, &ce) {
		return ce.Code
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		return ve.Code
	}
	if errors.Is(err, ErrNotFound) {
		return "NOT_FOUND"
	}
	return "INTERNAL"
}

// ListMembers returns a group's membership, cursor-paginated by user_id.
func (s *Store) ListMembers(ctx context.Context, tenant uuid.UUID, groupID uuid.UUID, cursor string, limit int) (Page[domain.Member], error) {
	limit = ClampLimit(limit)
	var page Page[domain.Member]
	err := s.WithTenant(ctx, tenant, func(tx pgx.Tx) error {
		if _, err := s.getGroupTx(ctx, tx, groupID); err != nil {
			return err
		}
		rows, err := tx.Query(ctx, `
			SELECT group_id, user_id, expires_at, created_at FROM members
			WHERE group_id = $1 AND user_id > $2 ORDER BY user_id LIMIT $3`,
			groupID, cursor, limit+1)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var m domain.Member
			if err := rows.Scan(&m.GroupID, &m.UserID, &m.ExpiresAt, &m.CreatedAt); err != nil {
				return err
			}
			page.Data = append(page.Data, m)
		}
		return rows.Err()
	})
	if err != nil {
		return page, err
	}
	if len(page.Data) > limit {
		page.Data = page.Data[:limit]
		page.HasMore = true
		page.NextCursor = page.Data[limit-1].UserID
	}
	return page, nil
}

// GroupsForUser returns the groups a user belongs to, cursor-paginated by
// group id — the reverse of ListMembers (queries members by user_id). RLS
// scopes the join to the caller's tenant.
func (s *Store) GroupsForUser(ctx context.Context, tenant uuid.UUID, userID string, cursor string, limit int) (Page[domain.Group], error) {
	limit = ClampLimit(limit)
	var page Page[domain.Group]
	args := []any{userID, limit + 1}
	where := "m.user_id = $1"
	if cursor != "" {
		cid, err := uuid.Parse(cursor)
		if err != nil {
			return page, &ValidationError{Code: CodeValidationFailed, Message: "invalid cursor"}
		}
		where += " AND g.id > $3"
		args = append(args, cid)
	}
	err := s.WithTenant(ctx, tenant, func(tx pgx.Tx) error {
		rows, err := tx.Query(ctx, `
			SELECT g.id, g.tenant_id, g.name, g.description, g.group_type, g.system, g.auto_generated, g.created_at, g.updated_at
			FROM members m JOIN groups g ON g.id = m.group_id
			WHERE `+where+` ORDER BY g.id LIMIT $2`, args...)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			g, err := scanGroup(rows)
			if err != nil {
				return err
			}
			page.Data = append(page.Data, g)
		}
		return rows.Err()
	})
	if err != nil {
		return page, err
	}
	if len(page.Data) > limit {
		page.Data = page.Data[:limit]
		page.HasMore = true
		page.NextCursor = page.Data[limit-1].ID.String()
	}
	return page, nil
}

func groupURN(tenant, id uuid.UUID) string {
	return fmt.Sprintf("wr:%s:rbac:group/%s", tenant, id)
}
