# ---------------------------------------------------------------------------
# Core / naming
# ---------------------------------------------------------------------------
variable "region" {
  description = "AWS region to deploy the Windrose platform into."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Prefix for all resource names and the Secrets Manager path (e.g. \"windrose-prod\"). Keep it short; used in resource names with length limits."
  type        = string
  default     = "windrose"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,24}$", var.name_prefix))
    error_message = "name_prefix must be lowercase alphanumeric/hyphen, start with a letter, and be <= 25 chars."
  }
}

variable "environment" {
  description = "Deployment environment label (dev | staging | prod). Used only for tagging."
  type        = string
  default     = "prod"
}

# ---------------------------------------------------------------------------
# Networking
# ---------------------------------------------------------------------------
variable "vpc_cidr" {
  description = "CIDR block for the platform VPC. Must be large enough for 3 public + 3 private /20 subnets."
  type        = string
  default     = "10.60.0.0/16"
}

variable "az_count" {
  description = "Number of Availability Zones to spread subnets across (3 recommended for HA)."
  type        = number
  default     = 3

  validation {
    condition     = var.az_count >= 2 && var.az_count <= 3
    error_message = "az_count must be 2 or 3."
  }
}

variable "single_nat_gateway" {
  description = "Use a single NAT gateway (cheaper, non-HA) instead of one per AZ. Set false for production HA."
  type        = bool
  default     = true
}

# ---------------------------------------------------------------------------
# EKS
# ---------------------------------------------------------------------------
variable "eks_version" {
  description = "Kubernetes control-plane version for the EKS cluster."
  type        = string
  default     = "1.30"
}

variable "node_instance_types" {
  description = "Instance types for the managed node group."
  type        = list(string)
  default     = ["m6i.xlarge"]
}

variable "node_capacity_type" {
  description = "ON_DEMAND or SPOT for the managed node group."
  type        = string
  default     = "ON_DEMAND"
}

variable "node_min_size" {
  description = "Minimum number of worker nodes."
  type        = number
  default     = 3
}

variable "node_max_size" {
  description = "Maximum number of worker nodes (autoscaler upper bound)."
  type        = number
  default     = 8
}

variable "node_desired_size" {
  description = "Desired number of worker nodes at creation."
  type        = number
  default     = 4
}

variable "node_disk_size" {
  description = "EBS root volume size (GiB) per worker node."
  type        = number
  default     = 100
}

variable "cluster_public_access" {
  description = "Expose the EKS API server publicly (still IAM-authenticated). Set false for private-only clusters reached via a bastion/VPN."
  type        = bool
  default     = true
}

variable "cluster_public_access_cidrs" {
  description = "CIDRs allowed to reach the public EKS API endpoint. Lock this down in production."
  type        = list(string)
  default     = ["0.0.0.0/0"]
}

# ---------------------------------------------------------------------------
# RDS PostgreSQL
# ---------------------------------------------------------------------------
variable "db_engine_version" {
  description = "PostgreSQL engine version for RDS."
  type        = string
  default     = "16.4"
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.m6g.large"
}

variable "db_allocated_storage" {
  description = "Initial RDS storage in GiB."
  type        = number
  default     = 100
}

variable "db_max_allocated_storage" {
  description = "Storage autoscaling ceiling in GiB (0 disables autoscaling)."
  type        = number
  default     = 500
}

variable "db_multi_az" {
  description = "Deploy RDS Multi-AZ (recommended for production)."
  type        = bool
  default     = true
}

variable "db_admin_username" {
  description = "Master/admin (DDL) username for RDS. The password is generated by Terraform and written to Secrets Manager."
  type        = string
  default     = "windrose_admin"
}

variable "db_backup_retention_days" {
  description = "Automated backup retention in days."
  type        = number
  default     = 7
}

variable "db_deletion_protection" {
  description = "Protect the RDS instance from accidental deletion."
  type        = bool
  default     = true
}

# ---------------------------------------------------------------------------
# ElastiCache (Redis/Valkey)
# ---------------------------------------------------------------------------
variable "redis_node_type" {
  description = "ElastiCache node type."
  type        = string
  default     = "cache.m6g.large"
}

variable "redis_engine" {
  description = "ElastiCache engine: \"redis\" or \"valkey\"."
  type        = string
  default     = "redis"
}

variable "redis_engine_version" {
  description = "ElastiCache engine version."
  type        = string
  default     = "7.1"
}

variable "redis_replicas_per_node_group" {
  description = "Number of read replicas per shard (>=1 enables automatic failover)."
  type        = number
  default     = 1
}

# ---------------------------------------------------------------------------
# MSK (Kafka)
# ---------------------------------------------------------------------------
variable "kafka_version" {
  description = "Apache Kafka version for MSK."
  type        = string
  default     = "3.6.0"
}

variable "kafka_broker_count" {
  description = "Number of MSK broker nodes. Must be a multiple of the number of AZs (subnets)."
  type        = number
  default     = 3
}

variable "kafka_broker_instance_type" {
  description = "MSK broker instance type."
  type        = string
  default     = "kafka.m5.large"
}

variable "kafka_broker_ebs_size" {
  description = "EBS volume size (GiB) per MSK broker."
  type        = number
  default     = 100
}

variable "kafka_sasl_username" {
  description = "SASL/SCRAM username the platform uses to connect to MSK. The password is generated by Terraform and stored in Secrets Manager."
  type        = string
  default     = "windrose"
}

# ---------------------------------------------------------------------------
# ECR
# ---------------------------------------------------------------------------
variable "create_ecr" {
  description = "Create one ECR repository per service (from services.yaml). Set false when publishing images to an external registry (GHCR, etc.)."
  type        = bool
  default     = false
}

variable "service_names" {
  description = "Service/image names — the source of truth is deploy/services.yaml. One ECR repo is created per entry when create_ecr = true."
  type        = list(string)
  default = [
    "identity-service",
    "rbac-service",
    "ingestion-service",
    "dataset-service",
    "realtime-hub",
    "agent-runtime",
    "memory-service",
    "case-service",
    "tool-registry",
    "mcp-gateway",
    "ai-gateway",
    "pipeline-orchestrator",
    "experiment-service",
    "inference-service",
    "query-service",
    "semantic-service",
    "chart-service",
    "usage-service",
    "audit-service",
    "notification-service",
    "eval-service",
    "bff-graphql",
    "ui-web",
  ]
}

# ---------------------------------------------------------------------------
# IRSA / workload identity
# ---------------------------------------------------------------------------
variable "workload_namespace" {
  description = "Kubernetes namespace the Windrose services run in (used to scope the S3 workload-identity IRSA trust policy)."
  type        = string
  default     = "windrose"
}

variable "external_secrets_namespace" {
  description = "Namespace the External Secrets Operator runs in."
  type        = string
  default     = "external-secrets"
}

variable "external_secrets_service_account" {
  description = "ServiceAccount name for the External Secrets Operator controller (matches the ESO Helm release)."
  type        = string
  default     = "external-secrets"
}

variable "workload_service_account" {
  description = "ServiceAccount name annotated onto S3-using services. \"*\" trusts every SA in workload_namespace."
  type        = string
  default     = "windrose-workload"
}

# ---------------------------------------------------------------------------
# Secrets — application-owned credential VALUES supplied later.
#
# This map is the seam for credentials Terraform does NOT itself generate:
# JWT signing material, SMTP creds, optional LLM API keys, ClickHouse, Vault,
# Keycloak admin, per-DB app-role passwords, etc. (see deploy/CONFIG.md).
#
# Infra-owned creds (POSTGRES_ADMIN_PASSWORD, the Redis auth token, and the
# Kafka SASL password) are GENERATED by Terraform and merged into the same
# Secrets Manager secret — do NOT put them here.
#
# Leave empty in source; supply via a git-ignored *.tfvars or CI (TF_VAR_secrets).
# ---------------------------------------------------------------------------
variable "secrets" {
  description = "Application-owned secret key/value pairs merged into the windrose-secrets Secrets Manager secret. Supply later via tfvars/CI; never commit real values."
  type        = map(string)
  sensitive   = true
  default     = {}
}
