package templates

// Default is one platform-default template body set for a mapping key.
type Default struct {
	Key     string
	Subject string
	HTML    string
	Text    string
}

// Defaults returns the platform-default templates (email channel, locale en)
// seeded at startup for every mapped event type. Tenant overrides shadow these
// (NOTIF-FR-041). In-app titles/bodies reuse the same bodies.
func Defaults() []Default {
	return []Default{
		{"case.assigned",
			"[Windrose] Case #{{.CaseNumber}} assigned to you",
			`<p>{{.AssignerName}} assigned case #{{.CaseNumber}} ({{.Severity}}) to you.</p><p><a href="{{.DeepLink}}">Open case</a></p>`,
			"{{.AssignerName}} assigned case #{{.CaseNumber}} ({{.Severity}}) to you.\nOpen: {{.DeepLink}}"},
		{"case.sla.breached",
			"[Windrose] SLA breached on case #{{.CaseNumber}}",
			`<p>SLA breached on case #{{.CaseNumber}} ({{.Severity}}).</p><p><a href="{{.DeepLink}}">Open case</a></p>`,
			"SLA breached on case #{{.CaseNumber}} ({{.Severity}}).\nOpen: {{.DeepLink}}"},
		{"case.unassigned",
			"[Windrose] Case #{{.CaseNumber}} unassigned",
			`<p>Case #{{.CaseNumber}} was unassigned ({{.Reason}}).</p><p><a href="{{.DeepLink}}">Open case</a></p>`,
			"Case #{{.CaseNumber}} was unassigned ({{.Reason}}).\nOpen: {{.DeepLink}}"},
		{"case.sla.warning",
			"[Windrose] SLA warning on case #{{.CaseNumber}}",
			`<p>SLA warning on case #{{.CaseNumber}}.</p><p><a href="{{.DeepLink}}">Open</a></p>`,
			"SLA warning on case #{{.CaseNumber}}.\nOpen: {{.DeepLink}}"},
		{"case.escalated",
			"[Windrose] Case #{{.CaseNumber}} escalated",
			`<p>Case #{{.CaseNumber}} ({{.Severity}}) escalated to you.</p><p><a href="{{.DeepLink}}">Open</a></p>`,
			"Case #{{.CaseNumber}} ({{.Severity}}) escalated to you.\nOpen: {{.DeepLink}}"},
		{"case.comment.added",
			"[Windrose] New comment on case #{{.CaseNumber}}",
			`<p>{{.CommenterName}} commented on case #{{.CaseNumber}}.</p><p><a href="{{.DeepLink}}">Open</a></p>`,
			"{{.CommenterName}} commented on case #{{.CaseNumber}}.\nOpen: {{.DeepLink}}"},
		{"chart.export.completed",
			"[Windrose] Chart export ready: {{.ChartName}}",
			`<p>Export of {{.ChartName}} is ready.</p><p><a href="{{.DeepLink}}">Download</a></p>`,
			"Export of {{.ChartName}} is ready.\n{{.DeepLink}}"},
		{"chart.export.failed",
			"[Windrose] Chart export failed: {{.ChartName}}",
			`<p>Export of {{.ChartName}} failed.</p><p><a href="{{.DeepLink}}">Retry</a></p>`,
			"Export of {{.ChartName}} failed.\n{{.DeepLink}}"},
		{"pipeline.run.failed",
			"[Windrose] Pipeline {{.PipelineName}} run failed",
			`<p>Pipeline {{.PipelineName}} run {{.RunID}} failed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Pipeline {{.PipelineName}} run {{.RunID}} failed.\n{{.DeepLink}}"},
		{"inference.failed",
			"[Windrose] Inference failed: {{.ModelName}}",
			`<p>Inference on {{.ModelName}} failed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Inference on {{.ModelName}} failed.\n{{.DeepLink}}"},
		{"pipeline.run.completed",
			"[Windrose] Pipeline {{.PipelineName}} completed",
			`<p>Pipeline {{.PipelineName}} completed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Pipeline {{.PipelineName}} completed.\n{{.DeepLink}}"},
		{"inference.completed",
			"[Windrose] Inference completed: {{.ModelName}}",
			`<p>Inference on {{.ModelName}} completed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Inference on {{.ModelName}} completed.\n{{.DeepLink}}"},
		{"ingestion.completed",
			"[Windrose] Ingestion completed: {{.DatasetName}}",
			`<p>Ingestion of {{.DatasetName}} completed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Ingestion of {{.DatasetName}} completed.\n{{.DeepLink}}"},
		{"ingestion.failed",
			"[Windrose] Ingestion failed: {{.DatasetName}}",
			`<p>Ingestion of {{.DatasetName}} failed.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Ingestion of {{.DatasetName}} failed.\n{{.DeepLink}}"},
		{"dataset.version.created",
			"[Windrose] New dataset version: {{.DatasetName}} {{.Version}}",
			`<p>Dataset {{.DatasetName}} version {{.Version}} created.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Dataset {{.DatasetName}} version {{.Version}} created.\n{{.DeepLink}}"},
		{"experiment.model.promoted",
			"[Windrose] Model promoted: {{.ModelName}}",
			`<p>Model {{.ModelName}} was promoted.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Model {{.ModelName}} was promoted.\n{{.DeepLink}}"},
		{"proposal.created",
			"[Windrose] Approval needed: {{.ProposalTitle}}",
			`<p>A proposal awaits your approval: {{.ProposalTitle}}.</p><p><a href="{{.DeepLink}}">Review</a></p>`,
			"A proposal awaits your approval: {{.ProposalTitle}}.\n{{.DeepLink}}"},
		{"proposal.approved",
			"[Windrose] Proposal approved: {{.ProposalTitle}}",
			`<p>Your proposal {{.ProposalTitle}} was approved.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Your proposal {{.ProposalTitle}} was approved.\n{{.DeepLink}}"},
		{"proposal.rejected",
			"[Windrose] Proposal rejected: {{.ProposalTitle}}",
			`<p>Your proposal {{.ProposalTitle}} was rejected.</p><p><a href="{{.DeepLink}}">View</a></p>`,
			"Your proposal {{.ProposalTitle}} was rejected.\n{{.DeepLink}}"},
		{"usage.budget.threshold",
			"[Windrose] Budget {{.BudgetName}} at {{.Percent}}%",
			`<p>Budget {{.BudgetName}} reached {{.Percent}}%.</p><p><a href="{{.DeepLink}}">Manage</a></p>`,
			"Budget {{.BudgetName}} reached {{.Percent}}%.\n{{.DeepLink}}"},
		{"usage.budget.exhausted",
			"[Windrose] Budget {{.BudgetName}} exhausted",
			`<p>Budget {{.BudgetName}} is exhausted.</p><p><a href="{{.DeepLink}}">Manage</a></p>`,
			"Budget {{.BudgetName}} is exhausted.\n{{.DeepLink}}"},
		{"identity.user.created",
			"[Windrose] Welcome, {{.UserName}}",
			`<p>Welcome to Windrose, {{.UserName}}.</p><p><a href="{{.DeepLink}}">Get started</a></p>`,
			"Welcome to Windrose, {{.UserName}}.\n{{.DeepLink}}"},
		{"rbac.grant.created",
			"[Windrose] Shared with you: {{.ResourceName}}",
			`<p>{{.ResourceName}} was shared with you.</p><p><a href="{{.DeepLink}}">Open</a></p>`,
			"{{.ResourceName}} was shared with you.\n{{.DeepLink}}"},
		{"security.cross_tenant_denied",
			"[Windrose] Security alert: cross-tenant access denied",
			`<p>A cross-tenant access attempt was denied at {{.Path}}.</p><p><a href="{{.DeepLink}}">Review</a></p>`,
			"A cross-tenant access attempt was denied at {{.Path}}.\n{{.DeepLink}}"},
		{"digest.info",
			"[Windrose] Your notification digest",
			`<p>You have {{.Count}} new notifications.</p>{{range .Items}}<p>{{.Title}} — <a href="{{.DeepLink}}">open</a></p>{{end}}`,
			"You have {{.Count}} new notifications.\n{{range .Items}}- {{.Title}} {{.DeepLink}}\n{{end}}"},
		{"digest.warning",
			"[Windrose] Your notification digest",
			`<p>You have {{.Count}} new notifications.</p>{{range .Items}}<p>{{.Title}} — <a href="{{.DeepLink}}">open</a></p>{{end}}`,
			"You have {{.Count}} new notifications.\n{{range .Items}}- {{.Title}} {{.DeepLink}}\n{{end}}"},
	}
}
